### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by WayneYe** [psf/black#1036]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Mac OSX Mojave
Python version: 3.7.4
*Black* version: black-19.3b0
Does also happen on master: yes

To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.

I ran into this issue:
```
black .
Traceback (most recent call last):
  File "/Users/yewe/.pyenv/versions/3.7.4/bin/black", line 10, in <module>
    sys.exit(patched_main())
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/black.py", line 3754, in patched_main
    main()
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/black.py", line 435, in main
    executor = ProcessPoolExecutor(max_workers=os.cpu_count())
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 556, in __init__
    pending_work_items=self._pending_work_items)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/Users/yewe/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 28] No space left on device
```

My env:
```
$python --version
Python 3.7.4
$uname -a
Darwin WYEC02XX6KCJG5J 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
$black --version
black, version 19.3b0
```

**Comment by zsol** [comment]
Did you check if you have enough `space left on device`? :)

**Comment by WayneYe** [comment]
@zsol of course i checked:
```
$ df -h
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   234Gi  202Gi   31Gi    87% 3047834 9223372036851727973    0%   /
```

**Comment by theSage21** [comment]
perhaps `/tmp` is full? Usually `/tmp` is mounted in RAM and capped at a certain limit?

**Comment by WayneYe** [comment]
@theSage21 yes, i think my `devfs` is 100%
```
df -h
Filesystem      Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1   466Gi  171Gi  291Gi    38% 2348771 9223372036852427036    0%   /
devfs          193Ki  193Ki    0Bi   100%     668                   0  100%   /dev
```

**Comment by WayneYe** [comment]
Let me close this issue for now since I cannot reproduce it anymore

**Comment by owang** [comment]
Did you ever figure out what was going on? I am having the same problem.

**Comment by stefanhoelzl** [comment]
you see this error message also when there are too many semaphores allocated.
Check with `ipcs -u -c` how many semaphores are allocated when this happens
