### ISSUE TITLE
Please update docstring for format_str() method

### ISSUE THREAD

**Issue by ProbonoBonobo** [psf/black#1064]
Operating system: Ubuntu 19.04
Python version: 3.7.4
*Black* version: 19.03b
Does also happen on master: Yes

I'm trying to use black programmatically to diff a code string before/after transformation. The `format_str` method appears to be my best bet for this, but that function takes a required keyword-only `mode` argument which is not described by the docstring. The type annotations in the signature of `format_str` helpfully suggest this argument must be a `black.FileMode` instance, but after reading several different docstrings I'm still at a loss how to appease this method.

Example usage of this method in the docstring, or at least an explanation of the `mode` parameter, would be really helpful.

```
>>> import black
>>> black.format_str(obfuscated)
Traceback (most recent call last):
  File "/home/kz/.local/pyenv/versions/3.7.3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-ae5fae166c69>", line 1, in <module>
    black.format_str(obfuscated)
TypeError: format_str() missing 1 required keyword-only argument: 'mode'
```

Ah no worries, we'll just check the docstring...

```
>>> help(black.format_str)
Help on function format_str in module black:
format_str(src_contents: str, *, mode: black.FileMode) -> str
    Reformat a string and return new contents.
    
    `line_length` determines how many characters per line are allowed.
```

I'm guessing the API has recently changed, because `line_length` is no longer present in the signature. Still, at least now we know the type of argument `mode` is expecting... we'll check the docstring for that.

```
>>> help(black.FileMode)
Help on class FileMode in module black:
class FileMode(builtins.object)
 |  FileMode(target_versions: Set[black.TargetVersion] = NOTHING, line_length: int = 88, string_normalization: bool = True, is_pyi: bool = False) -> None
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, other)
 |      Return self==value.
 |  
 |  __ge__(self, other)
 |      Automatically created by attrs.
 |  
 |  __gt__(self, other)
 |      Automatically created by attrs.
 |  
 |  __init__(self, target_versions: Set[black.TargetVersion] = NOTHING, line_length: int = 88, string_normalization: bool = True, is_pyi: bool = False) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __le__(self, other)
 |      Automatically created by attrs.
 |  
 |  __lt__(self, other)
 |      Automatically created by attrs.
 |  
 |  __ne__(self, other)
 |      Check equality and either forward a NotImplemented or return the result
 |      negated.
 |  
 |  __repr__(self)
 |      Automatically created by attrs.
 |  
 |  get_cache_key(self) -> str
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __annotations__ = {'is_pyi': <class 'bool'>, 'line_length': <class 'in...
 |  
 |  __attrs_attrs__ = (Attribute(name='target_versions', default=Facto...e...
 |  
 |  __hash__ = None
```

So if I'm reading this correctly, the `black.FileMode` class maps `black.TargetVersion` keys to some configuration settings. Ok, let's make a `black.TargetVersion` object...

```
>>> black.TargetVersion
<enum 'TargetVersion'>
>>> help(black.TargetVersion)
Help on class TargetVersion in module black:
class TargetVersion(enum.Enum)
 |  TargetVersion(value, names=None, *, module=None, qualname=None, type=None, start=1)
 |  
 |  An enumeration.
 |  
 |  Method resolution order:
 |      TargetVersion
 |      enum.Enum
 |      builtins.object
 |  
 |  Data and other attributes defined here:
 |  
 |  PY27 = <TargetVersion.PY27: 2>
 |  
 |  PY33 = <TargetVersion.PY33: 3>
 |  
 |  PY34 = <TargetVersion.PY34: 4>
 |  
 |  PY35 = <TargetVersion.PY35: 5>
 |  
 |  PY36 = <TargetVersion.PY36: 6>
 |  
 |  PY37 = <TargetVersion.PY37: 7>
 |  
 |  PY38 = <TargetVersion.PY38: 8>
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from enum.Enum:
 |  
 |  name
 |      The name of the Enum member.
 |  
 |  value
 |      The value of the Enum member.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from enum.EnumMeta:
 |  
 |  __members__
 |      Returns a mapping of member name->value.
 |      
 |      This mapping lists all enum members, including aliases. Note that this
 |      is a read-only view of the internal mapping.

>>> type(black.TargetVersion['PY37']) 
<enum 'TargetVersion'>

```

Phew,  alright we have a TargetVersion object. Let's turn it into a file mode object...
```
>>>  black.FileMode(black.TargetVersion['PY37'])                                               
FileMode(target_versions=<TargetVersion.PY37: 7>, line_length=88, string_normalization=True, is_pyi=False)

```

Cool. Looks like a FileMode. Let's try this again... 

```
black.format_str("def square   (    x     ) :   \n        return x * x       \n\n", mode=black.FileMode(black.TargetVersion['PY37']))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-6a7482dec2f5> in <module>
----> 1 black.format_str("def square   (    x     ) :   \n        return x * x       \n\n", mode=black.FileMode(black.TargetVersion['PY37']))

~/.local/pyenv/versions/3.7.3/lib/python3.7/site-packages/black.py in format_str(src_contents, mode)
    667     `line_length` determines how many characters per line are allowed.
    668     """
--> 669     src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
    670     dst_contents = ""
    671     future_imports = get_future_imports(src_node)

~/.local/pyenv/versions/3.7.3/lib/python3.7/site-packages/black.py in lib2to3_parse(src_txt, target_versions)
    741         src_txt += "\n"
    742 
--> 743     for grammar in get_grammars(set(target_versions)):
    744         drv = driver.Driver(grammar, pytree.convert)
    745         try:

TypeError: 'TargetVersion' object is not iterable

```

😑 I give up...

**Comment by ProbonoBonobo** [comment]
Noted! Thanks for your attention to this.
