### ISSUE TITLE
Black raises [WinError 5] when running from virtual environment created by `python -m venv .venv` on Windows 8.1 with python 3.7.2

### ISSUE THREAD

**Issue by MarcSkovMadsen** [psf/black#1126]
Black raises [WinError 5] when running from virtual environment created by `python -m venv .venv` on Windows 8.1 with python 3.7.2 (64 bit). There is no problem when running from a virtual environment created by `virtualenv .venv`.

**To Reproduce**

1. cd into the root of your root folder with some python files that will be formatted by black.
2. create your virtual environement `python -m venv .venv`
2. activate your environment `source .venv/Scripts/activate`
3. run black `black .`

```bash
$ black .
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 93, in get
    with self._rlock:
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
PermissionError: [WinError 5] Access is denied
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 93, in get
    with self._rlock:
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
PermissionError: [WinError 5] Access is denied
Process SpawnProcess-3:
Traceback (most recent call last):
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 93, in get
    with self._rlock:
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
PermissionError: [WinError 5] Access is denied
error: cannot format C:\Users\masma\source\repos\orsteddcsmarketsanalytics\apps\portfolio_analytics\.venv2\Lib\_bootlocale.py: A process in the process pool was terminated abruptly while the future was running or pending.Process SpawnProcess-4:

Traceback (most recent call last):
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\process.py", line 226, in _process_worker
    call_item = call_queue.get(block=True)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\queues.py", line 93, in get
    with self._rlock:
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\multiprocessing\synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
PermissionError: [WinError 5] Access is denied
error: cannot format C:\Users\masma\source\repos\orsteddcsmarketsanalytics\apps\portfolio_analytics\.venv2\Lib\enum.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\masma\source\repos\orsteddcsmarketsanalytics\apps\portfolio_analytics\.venv2\Lib\posixpath.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\masma\source\repos\orsteddcsmarketsanalytics\apps\portfolio_analytics\.venv2\Lib\encodings\big5hkscs.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\masma\source\repos\orsteddcsmarketsanalytics\apps\portfolio_analytics\.venv2\Lib\encodings\iso2022_jp_1.py: A process in the process pool was terminated abruptly while the future was running or pending.
error: cannot format C:\Users\masma\source\repos\orsteddcsmarketsanalytics\apps\portfolio_analytics\.venv2\Lib\fnmatch.py: A process in the process pool was terminated abruptly while the future was running or pending.
.....
.....
```

**Expected behavior** A clear and concise description of what you expected to happen.

No exception.

**Environment (please complete the following information):**

- Version: 19.10b0 (and older)
- OS and Python version: Windows 8.1

**Does this bug also happen on master?** 

Yes. I cloned master and followed the instructions

![image](https://user-images.githubusercontent.com/42288570/67927200-4adc0c00-fbb8-11e9-8554-eb27853e28a1.png)

**Additional context**

The error is not produced when running from virtual environment created by virtualenv `virtualenv .venv`

**Comment by MarcSkovMadsen** [comment]
I saw this post https://bugs.python.org/issue35797 and upgraded to python 3.7.4. That solved the issue for me.
