### ISSUE TITLE
error installing black via pip

### ISSUE THREAD

**Issue by shahzebsiddiqui** [psf/black#1176]
Issue installing black

I am using a pipenv to install black and it is blowing up horribly during installation

```
(buildtest-framework) $ pip -V
pip 19.3.1 from /u/users/ssi29/.local/share/virtualenvs/buildtest-framework-LDt8wyRf/lib/python3.7/site-packages/pip (python 3.7)
```

```
(buildtest-framework) $ pip install black | more
Collecting black
  Using cached https://files.pythonhosted.org/packages/fd/bb/ad34bbc93d1bea3de086d7c59e528d4a503ac8fe318bd1fa48605584c3d2/black-19.10b0-py36-none-any.whl
Collecting regex
  Using cached https://files.pythonhosted.org/packages/fc/1d/13cc7d174cd2d05808abac3f5fb37433e30c4cd93b152d2a9c09c926d7e8/regex-2019.11.1.tar.gz
Requirement already satisfied: click>=6.5 in /u/users/ssi29/.local/share/virtualenvs/buildtest-framework-LDt8wyRf/lib/python3.7/site-packages (from black) (7.0)
Requirement already satisfied: attrs>=18.1.0 in /u/users/ssi29/.local/share/virtualenvs/buildtest-framework-LDt8wyRf/lib/python3.7/site-packages (from black) (19.3.0
)
Requirement already satisfied: appdirs in /u/users/ssi29/.local/share/virtualenvs/buildtest-framework-LDt8wyRf/lib/python3.7/site-packages (from black) (1.4.3)
Requirement already satisfied: pathspec<1,>=0.6 in /u/users/ssi29/.local/share/virtualenvs/buildtest-framework-LDt8wyRf/lib/python3.7/site-packages (from black) (0.6
.0)
Requirement already satisfied: toml>=0.9.4 in /u/users/ssi29/.local/share/virtualenvs/buildtest-framework-LDt8wyRf/lib/python3.7/site-packages (from black) (0.10.0)
Requirement already satisfied: typed-ast>=1.4.0 in /u/users/ssi29/.local/share/virtualenvs/buildtest-framework-LDt8wyRf/lib/python3.7/site-packages (from black) (1.4
.0)
Building wheels for collected packages: regex
  Building wheel for regex (setup.py): started

    /scratch/ccsWkVXk.s:107918: Error: unknown .loc sub-directive `view'
    /scratch/ccsWkVXk.s:107918: Error: unknown pseudo-op: `.lvu32775'
    /scratch/ccsWkVXk.s:107919: Error: unknown .loc sub-directive `view'
    /scratch/ccsWkVXk.s:107919: Error: unknown pseudo-op: `.lvu32776'
    /scratch/ccsWkVXk.s:107922: Error: unknown .loc sub-directive `view'
    /scratch/ccsWkVXk.s:107922: Error: unknown pseudo-op: `.lvu32777'
    /scratch/ccsWkVXk.s:107930: Error: unknown .loc sub-directive `view'
    /scratch/ccsWkVXk.s:107930: Error: unknown pseudo-op: `.lvu32778'
    /scratch/ccsWkVXk.s:107936: Error: unknown .loc sub-directive `view'
    /scratch/ccsWkVXk.s:107936: Error: unknown pseudo-op: `.lvu32779'
    /scratch/ccsWkVXk.s:107938: Error: unknown .loc sub-directive `view'
    /scratch/ccsWkVXk.s:107938: Error: unknown pseudo-op: `.lvu32780'
    /scratch/ccsWkVXk.s:107944: Error: unknown .loc sub-directive `view'

```

**Comment by shahzebsiddiqui** [comment]
my next step was to clone black repo and tried running ``black.py`` and this is handing

How can i use this if i want to just clone the repo.

```
(buildtest-framework) $ ls
blackd.py  blib2to3         docs     MANIFEST.in  Pipfile       plugin     pyproject.toml  readthedocs.yml  setup.py
black.py   CONTRIBUTING.md  LICENSE  mypy.ini     Pipfile.lock  profiling  README.md       setup.cfg        tests
(buildtest-framework) $ chmod +x black.py
(buildtest-framework) $ ./black.py --help
```

**Comment by shahzebsiddiqui** [comment]
Tried installing via Python 2.7 in a different cluster and got an error
```
[sms1990@comet-ln2 ~]$ pip install --user black
Collecting black
  Using cached https://files.pythonhosted.org/packages/b0/dc/ecd83b973fb7b82c34d828aad621a6e5865764d52375b8ac1d7a45e23c8d/black-19.10b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-qPwYtz/black/setup.py", line 12
        def get_long_description() -> str:
                                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qPwYtz/black
You are using pip version 7.1.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I dont have much control over this machine and dont have Python 3.x so this was not successful.

**Comment by shahzebsiddiqui** [comment]
@ambv

**Comment by hugovk** [comment]
Black supports Python 3.6+ only, but I recommend upgrading pip for Python 2, newer versions should give better messages.

    python -m pip install -U pip

The original issue looks related to https://github.com/psf/black/issues/1112, where you don't have a compiler set up for the regex dependency.

**Comment by shahzebsiddiqui** [comment]
ok i got a workaround by downloading the file https://github.com/psf/black/releases/download/19.10b0/black and this worked out of the box.

The first machine i tried was using Python 3.7.4 and pip failed.

You can close this issue for now.
