### ISSUE TITLE
The path python3.7 (from --python=python3.7) does not exist

### ISSUE THREAD

**Issue by nibu147** [psf/black#1242]
I'm trying to use black on pre-commit, by using this settings:

```
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
```
Unfortuntely I get this error: (it doesn't happen if I try to format with python3.6)

```
### version information

pre-commit version: 1.21.0
sys.version:
    2.7.15 (default, Jan 12 2019, 21:07:57) 
    [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
sys.executable: /usr/local/opt/python@2/bin/python2.7
os.name: posix
sys.platform: darwin


### error information


An unexpected error has occurred: CalledProcessError: command: ('/usr/local/opt/python@2/bin/python2.7', '-mvirtualenv', '/Users/user name/.cache/pre-commit/repoi4s0y8j6/py_env-python3.7', '-p', 'python3.7')
return code: 3
expected return code: 0
stdout:
    The path python3.7 (from --python=python3.7) does not exist

stderr: (none)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 72, in error_handler
    yield
  File "/usr/local/lib/python2.7/site-packages/pre_commit/main.py", line 344, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 292, in run
    install_hook_envs(hooks, store)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/repository.py", line 220, in install_hook_envs
    hook.install()
  File "/usr/local/lib/python2.7/site-packages/pre_commit/repository.py", line 98, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/usr/local/lib/python2.7/site-packages/pre_commit/languages/python.py", line 169, in install_environment
    _make_venv(env_dir, python)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/languages/python.py", line 181, in make_venv
    cmd_output_b(*cmd, env=env, cwd='/')
  File "/usr/local/lib/python2.7/site-packages/pre_commit/util.py", line 141, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
CalledProcessError: command: ('/usr/local/opt/python@2/bin/python2.7', '-mvirtualenv', '/Users/user name/.cache/pre-commit/repoi4s0y8j6/py_env-python3.7', '-p', 'python3.7')
return code: 3
expected return code: 0
stdout:
    The path python3.7 (from --python=python3.7) does not exist

stderr: (none)
```

Any ideas on how to solve it?

**Comment by JelleZijlstra** [comment]
Sounds like you need to install Python 3.7.

**Comment by nibu147** [comment]
it's actually installed on my machine (python3.7 command works in my shell), but it seems it's not found.
what could be the reason?
thanks!

**Comment by mastershaig** [comment]
> it's actually installed on my machine (python3.7 command works in my shell), but it seems it's not found.
> what could be the reason?
> thanks!

same

**Comment by JelleZijlstra** [comment]
Perhaps the issue is with how pre-commit finds the binary to run.

**Comment by ichard26** [comment]
Closing since there has been no activity on this user support issue for over two months. I'm open to reopening (pun intended!) if there's activity.
