### ISSUE TITLE
Unknown symbol on fresh install

### ISSUE THREAD

**Issue by tommyjcarpenter** [psf/black#1260]
On a fresh install of black, when opening vim for the first time, I get:
```
Error detected while processing /home/tommy/.vim/bundle/black/plugin/black.vim:
line  147:
Traceback (most recent call last):
  File "<string>", line 63, in <module>
  File "/home/tommy/.vim/black/lib/python3.7/site-packages/black.py", line 15, in <module>
    import regex as re
  File "/home/tommy/.vim/black/lib/python3.7/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/home/tommy/.vim/black/lib/python3.7/site-packages/regex/regex.py", line 403, in <module>
    import regex._regex_core as _regex_core
  File "/home/tommy/.vim/black/lib/python3.7/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: /home/tommy/.vim/black/lib/python3.7/site-packages/regex/_regex.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type
Press ENTER or type command to continue
```

**Environment (please complete the following information):**

- Version: whatever `Plugin 'python/black'` in vimrc does
- OS and Python version: Arch Linux/Python 3.7.4

**Comment by tommyjcarpenter** [comment]
sorry, this was due to a weird state in Docker. No problem!
