### ISSUE TITLE
black.vim error when open file under directory site-packages.

### ISSUE THREAD

**Issue by roachsinai** [psf/black#1282]
Vim open file with black plugin error under pyenv's python `site-packages` directory(Even didn't activate the pyenv environment):

```
hmank ~/./v/3/e/n/l/p/s/torch » vim some_file      
处理 /home/roach/.vim/plugged/black/plugin/black.vim 时发生错误:
第  147 行:
Traceback (most recent call last):
  File "<string>", line 63, in <module>
  File "/usr/lib/python3.8/site-packages/black.py", line 3, in <module>
    from concurrent.futures import Executor, ProcessPoolExecutor
  File "/usr/lib/python3.8/concurrent/futures/__init__.py", line 44, in __getattr__
    from .process import ProcessPoolExecutor as pe
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 53, in <module>
    import multiprocessing as mp
  File "/home/roach/.pyenv/versions/3.7.4/envs/nn/lib/python3.7/site-packages/torch/multiprocessing/__init__.py", line 16, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
请按 ENTER 或其它命令继续
```

No error when under system python `site-packages` directory: `/usr/lib/python3.8/site-packages`(even activated the virtual environment).

**To Reproduce** Steps to reproduce the behavior:

Use pyenv and black VIM plugin on Manjaro Linux.

**Environment:**

- Version: python-black 19.10b0-1
- OS and Python version: Linux/Python 3.7.4

**Comment by zsol** [comment]
I suspect this happens because of a problem with these python environments. importing `multiprocessing` should not result in `import torch`, especially not from within a different python version.

**Comment by roachsinai** [comment]
The reason of `import torch` should be I do `vim some_file` under the directory: `site-packages/torch`.

The error I do it at `site-packages` no `import torch`:

```
hmank ~ » cd ~/.pyenv/versions/3.7.4/envs/nn/lib/python3.7/site-packages/
hmank ~/./v/3/e/n/l/p/site-packages » vim some_file
处理 /home/roach/.vim/plugged/black/plugin/black.vim 时发生错误:
第  147 行:
Traceback (most recent call last):
  File "<string>", line 63, in <module>
  File "/usr/lib/python3.8/site-packages/black.py", line 45, in <module>
    from typed_ast import ast3, ast27
  File "/home/roach/.pyenv/versions/3.7.4/envs/nn/lib/python3.7/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: cannot import name '_ast3' from 'typed_ast' (/home/roach/.pyenv/versions/3.7.4/envs/nn/lib/python3.7/site-packages/typed_ast/__init__.py)
请按 ENTER 或其它命令继续
```

**Comment by JelleZijlstra** [comment]
This sounds like a broken user environment, not a bug in Black.
