### ISSUE TITLE
`Cannot parse: 3:30: line: Tuple[bool, str] = False, ''`

### ISSUE THREAD

**Issue by SamuelMarks** [psf/black#1693]
```
$ python -m black a.py 
error: cannot format a.py: Cannot parse: 3:30: line: Tuple[bool, str] = False, ''
Oh no! 💥 💔 💥
1 file failed to reformat.
$ head a.py 
from typing import Tuple

line: Tuple[bool, str] = False, ''
$ python --version
Python 3.9.0rc1
$ python -m black --version
__main__.py, version 20.8b1
```

What am I doing wrong?

**Comment by bbugyi200** [comment]
I was able to repreduce. Note that the following works fine:
```python
from typing import Tuple

line: Tuple[bool, str] = (False, '')
```
It seems to be the lack of parens that is throwing `lib2to3` off. Without the parens, running `black -v a.py` gives me the following output:
```
Traceback (most recent call last):
  File "/home/bryan/Sync/var/projects/black/src/black/__init__.py", line 673, in reformat_one
    if changed is not Changed.CACHED and format_file_in_place(
  File "/home/bryan/Sync/var/projects/black/src/black/__init__.py", line 816, in format_file_in_place
    dst_contents = format_file_contents(src_contents, fast=fast, mode=mode)
  File "/home/bryan/Sync/var/projects/black/src/black/__init__.py", line 937, in format_file_contents
    dst_contents = format_str(src_contents, mode=mode)
  File "/home/bryan/Sync/var/projects/black/src/black/__init__.py", line 977, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/home/bryan/Sync/var/projects/black/src/black/__init__.py", line 1086, in lib2to3_parse
    raise exc from None
black.InvalidInput: Cannot parse: 3:30: line: Tuple[bool, str] = False, ''
error: cannot format /tmp/temp.py: Cannot parse: 3:30: line: Tuple[bool, str] = False, ''
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Comment by JelleZijlstra** [comment]
This is #1189.
