### ISSUE TITLE
Fuzz tests fail when Python3.9.

### ISSUE THREAD

**Issue by hadialqattan** [psf/black#1749]
Fuzz tests fail when Python3.9.

**Environment:**

- Version: PR #1748 
- OS and Python version: Linux/Python 3.9

**Additional context** `fuzz.yml` workflow log:
```log
2020-10-08T14:09:27.5958926Z ##[group]Run coverage run fuzz.py
2020-10-08T14:09:27.5959549Z �[36;1mcoverage run fuzz.py�[0m
2020-10-08T14:09:27.5959957Z �[36;1mcoverage report�[0m
2020-10-08T14:09:27.6010681Z shell: /bin/bash -e {0}
2020-10-08T14:09:27.6011016Z env:
2020-10-08T14:09:27.6011463Z   pythonLocation: /opt/hostedtoolcache/Python/3.9.0/x64
2020-10-08T14:09:27.6011987Z ##[endgroup]
2020-10-08T14:09:47.8690169Z <string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
2020-10-08T14:09:47.8692080Z <string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
2020-10-08T14:09:47.8701479Z <string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
2020-10-08T14:10:08.4345243Z   File "<string>", line 1
2020-10-08T14:10:08.4480315Z SyntaxError: unexpected character after line continuation character
2020-10-08T14:10:08.4480822Z 
2020-10-08T14:10:08.4481304Z The above exception was the direct cause of the following exception:
2020-10-08T14:10:08.4481703Z 
2020-10-08T14:10:08.4482182Z Traceback (most recent call last):
2020-10-08T14:10:08.4484636Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 110, in draw_symbol
2020-10-08T14:10:08.4485686Z     compile(
2020-10-08T14:10:08.4486472Z SystemError: <built-in function normalize> returned a result with an error set
2020-10-08T14:10:08.4486922Z 
2020-10-08T14:10:08.4487358Z The above exception was the direct cause of the following exception:
2020-10-08T14:10:08.4487755Z 
2020-10-08T14:10:08.4488077Z Traceback (most recent call last):
2020-10-08T14:10:08.4488636Z   File "/home/runner/work/black/black/fuzz.py", line 59, in <module>
2020-10-08T14:10:08.4489219Z     test_idempotent_any_syntatically_valid_python()
2020-10-08T14:10:08.4490030Z   File "/home/runner/work/black/black/fuzz.py", line 17, in test_idempotent_any_syntatically_valid_python
2020-10-08T14:10:08.4490802Z     max_examples=1000,  # roughly 1k tests/minute, or half that under coverage
2020-10-08T14:10:08.4491959Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesis/core.py", line 1162, in wrapped_test
2020-10-08T14:10:08.4532107Z     raise the_error_hypothesis_found
2020-10-08T14:10:08.4533555Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 89, in do_draw
2020-10-08T14:10:08.4534329Z     result = super().do_draw(data)
2020-10-08T14:10:08.4536372Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 146, in do_draw
2020-10-08T14:10:08.4537140Z     self.draw_symbol(data, start, state)
2020-10-08T14:10:08.4539320Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
2020-10-08T14:10:08.4540796Z     super().draw_symbol(data, symbol, draw_state)
2020-10-08T14:10:08.4541909Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 174, in draw_symbol
2020-10-08T14:10:08.4542695Z     self.draw_symbol(data, e, draw_state)
2020-10-08T14:10:08.4543797Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
2020-10-08T14:10:08.4544899Z     super().draw_symbol(data, symbol, draw_state)
2020-10-08T14:10:08.4545993Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 174, in draw_symbol
2020-10-08T14:10:08.4547200Z     self.draw_symbol(data, e, draw_state)
2020-10-08T14:10:08.4548777Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
2020-10-08T14:10:08.4549599Z     super().draw_symbol(data, symbol, draw_state)
2020-10-08T14:10:08.4550688Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 174, in draw_symbol
2020-10-08T14:10:08.4551459Z     self.draw_symbol(data, e, draw_state)
2020-10-08T14:10:08.4553867Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
2020-10-08T14:10:08.4554706Z     super().draw_symbol(data, symbol, draw_state)
2020-10-08T14:10:08.4555811Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 174, in draw_symbol
2020-10-08T14:10:08.4556861Z     self.draw_symbol(data, e, draw_state)
2020-10-08T14:10:08.4557977Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 107, in draw_symbol
2020-10-08T14:10:08.4558799Z     super().draw_symbol(data, symbol, draw_state)
2020-10-08T14:10:08.4559871Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 174, in draw_symbol
2020-10-08T14:10:08.4560643Z     self.draw_symbol(data, e, draw_state)
2020-10-08T14:10:08.4561734Z   File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 119, in draw_symbol
2020-10-08T14:10:08.4562495Z     raise Exception(
2020-10-08T14:10:08.4563815Z Exception: unexpected error while attempting to compile 'pass;importūą.𤳪ŋ냤ŏᩘGŌı\t\t\x0c\t.ĵ.춠𭝙scÈ  \x0c\x0c\x0c\t\x0c\t\t  \x0c \x0c\x0c\t\t \x0c \t\t\t\t \t\x0c\t   \t \\\t\x0c\x0c\t\r\n,slĢŢ.Ĥĸok\\ \t \t\t\n\x0c\x0c\t\x0c\t.ŔĿ,MwŉÀ\\\t\x0c\x0c\n#Ö\x90¤' in mode=single
```

**Comment by hadialqattan** [comment]
@Zac-HD What do you think about that?

**Comment by Zac-HD** [comment]
Well, I've shipped a patch to Hypothesmith which will ascii-escape the failing string if this happens again, because for whatever reason I can't reproduce it with the `repr` and thus suspect that some codepoints were modified along the copy-and-paste chain.

It's taken me a while to dig into this, but here's the situation as I understand it.

- `SyntaxError: unexpected character after line continuation character` is the first error we encounter.  This is a known possibility from the design of Hypothesmith - we use an over-approximation of Python's grammar, and then filter by "does `compile()` give a `SyntaxError`.  However...

- That triggers a `SystemError: <built-in function normalize> returned a result with an error set`.  IMO this is probably an upstream bug in CPython - `unicodedata.normalize()` should never raise an error when called on a string.  I haven't been able to reproduce it locally, but that could be some combination of windows laptop and little CPU-time spent on the effort so far - I'll try again with [HypoFuzz](https://hypofuzz.com/) when I get home on the weekend.

- and the final `Exception: unexpected error while attempting to compile ...` is a diagnostic I added in response to https://github.com/Zac-HD/stdlib-property-tests/issues/14, which in hindsight looks like it might have been exactly this same issue.  Hopefully the latest diagnostics will help solve it for good!

**Comment by hadialqattan** [comment]
@Zac-HD I appreciate your time and efforts, I'm gonna try to help you fix this issue, greetings.

**Comment by ichard26** [comment]
None of the issues can be reproduced on modern Python 3.9 and Hypothesmith: https://github.com/ichard26/black/runs/1607360235?check_suite_focus=true

I'll close this issue and submit a PR to enable fuzzing on Python 3.9 in CI. Thanks @hadialqattan and @Zac-HD for your efforts!

**Comment by Zac-HD** [comment]
Ah, it looks like I reported [BPO-42218](https://bugs.python.org/issue42218) and [worked around it in Hypothesmith](https://github.com/Zac-HD/hypothesmith/blob/master/CHANGELOG.md#017---2020-11-15) without updating here.  Thanks @ichard26 for retrying 💖
