### ISSUE TITLE
Black-compatible config for isort incurs `TomlDecodeError`

### ISSUE THREAD

**Issue by simaki** [psf/black#1917]
**Describe the bug**

[The compatible config of pyproject.toml for isort](https://github.com/psf/black/blob/master/docs/compatible_configs/isort/pyproject.toml) raises `TomlDecodeError`.

**To Reproduce**

Create the following `pyproject.toml` (along with `foo/__init__.py`).

```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = "bar"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = black
```

Install.

```sh
pip install .
```

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/toml/decoder.py", line 918, in load_value
    v = int(v, 0)
ValueError: invalid literal for int() with base 0: 'black'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
    name = self._p.identify(requirement)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
    return dependency.name
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
    return self.candidate.name
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
    return self.project_name
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
    self._name = canonicalize_name(self.dist.project_name)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 523, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 34, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 504, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/pyproject.py", line 75, in load_pyproject_toml
    pp_toml = toml.load(f)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
pip._vendor.toml.decoder.TomlDecodeError: invalid literal for int() with base 0: 'black' (line 16 column 1 char 247)
```

**Expected behavior** 

`pyproject.toml` is successfully decoded and the package is installed.

**Environment**

- Version: master
- OS and Python version: macOS Big Sur / Python 3.9.1 / Poetry version 1.1.4

**Possible Solution**

Replacing `profile = black` with `profile = 'black'` resolved this in my environment.
I'll make a pull-request to do this.

**Comment by erikr** [comment]
Are the docs not yet updated to reflect this change? https://github.com/psf/black/blob/master/docs/compatible_configs.md#formats

**Comment by ichard26** [comment]
I'm a little confused, where is the error still present? The PR changed the raw example configuration file @ https://github.com/psf/black/blob/master/docs/compatible_configs/isort/pyproject.toml

**Comment by erikr** [comment]
Sorry for being imprecise.

At https://github.com/psf/black/blob/master/docs/compatible_configs.md#why-those-options-above, both this text

>  If only isort >= 5 is used you can add `profile = black` instead of all the options since profiles are available and do the configuring for you.

and the example `pyproject.toml` syntax
```
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
```

do not have quotes around values of each argument. Using this syntax results in the error described in this issue.

Should the syntax in `pyproject.toml` should instead be the following?

```
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
```
or
```
[tool.isort]
profile = "black"
```

Single or double quotes seem interchangeable here.

**Comment by ichard26** [comment]
Oh good catch with the "If only isort >= 5 is used you can add profile = black" line, that needs fixing. Honestly I'm not happy with the black compatible configuration docs right now since isort has 2 ways of being configured to work with Black and they aren't represented the same way in the docs. For the numbers and boolean, I'm pretty sure that since those are special types, they won't / shouldn't have quotes around them
