### ISSUE TITLE
Pre-commit fails when setting up the black environment

### ISSUE THREAD

**Issue by imor-de** [psf/black#2059]
**Describe the bug**
pre-commit fails when setting up the black environment.

**To Reproduce** 
I configured black in my pre-commit-config.yaml as
```  
- repo: https://github.com/psf/black
    rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
    hooks:
      - id: black
```
While installing with `pre-commit install-hook` I get the following error:

```
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/imor-de/.cache/pre-commit/repo795zf16a
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'error'
    
stderr:
        ERROR: Command errored out with exit status 1:
         command: /Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/bin/python /Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/tmp03jr49mg
             cwd: /private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-req-build-zcx3q_6f
        Complete output (46 lines):
        /private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/git.py:88: UserWarning: "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-req-build-zcx3q_6f" is shallow and may cause errors
          warnings.warn(f'"{wd.path}" is shallow and may cause errors')
        Traceback (most recent call last):
          File "/Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
            main()
          File "/Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 48, in <module>
            setup(
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "/usr/local/opt/asdf/installs/python/3.9.2/lib/python3.9/distutils/core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 434, in __init__
            _Distribution.__init__(self, {
          File "/usr/local/opt/asdf/installs/python/3.9.2/lib/python3.9/distutils/dist.py", line 292, in __init__
            self.finalize_options()
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 743, in finalize_options
            ep(self)
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 750, in _finalize_setup_keywords
            ep.load()(self, ep.name, value)
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/integration.py", line 24, in version_keyword
            dist.metadata.version = _get_version(config)
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
            parsed_version = _do_parse(config)
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
            version = _version_from_entrypoints(config) or _version_from_entrypoints(
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
            version = _call_entrypoint_fn(root, config, ep.load())
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
            return fn(root, config=config)
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/git.py", line 127, in parse
            node_date = wd.get_head_date() or date.today()
          File "/private/var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/pip-build-env-p1l6kgqx/overlay/lib/python3.9/site-packages/setuptools_scm/git.py", line 67, in get_head_date
            return datetime.strptime(date_part, r"%Y-%m-%d").date()
          File "/usr/local/opt/asdf/installs/python/3.9.2/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
            tt, fraction, gmtoff_fraction = _strptime(data_string, format)
          File "/usr/local/opt/asdf/installs/python/3.9.2/lib/python3.9/_strptime.py", line 349, in _strptime
            raise ValueError("time data %r does not match format %r" %
        ValueError: time data 'gpg: Signature made Wed Aug 26 17:50:45 2020 CES' does not match format '%Y-%m-%d'
        ----------------------------------------
    WARNING: Discarding file:///Users/imor-de/.cache/pre-commit/repo795zf16a. Command errored out with exit status 1: /Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/bin/python /Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/tmp03jr49mg Check the logs for full command output.
    ERROR: Command errored out with exit status 1: /Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/bin/python /Users/imor-de/.cache/pre-commit/repo795zf16a/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/zs/ydvqpbz95pb3_l60_2vk2k0h0000gn/T/tmp03jr49mg Check the logs for full command output.
    
Check the log at /Users/imor-de/.cache/pre-commit/pre-commit.log
```
**Expected behavior** 
pre-commit should install black.

**Environment (please complete the following information):**

- Version: 20.8b1
- OS version: macOS Big Sur Version 11.2.3
- Python version: 3.8.7
- pre-commit: 2.10.1

**Additional context** 

- I can't explain, why gpg signatures from commit massages are responsible for this problem. Black is a formatter for python ... what have commit massages to do with this? 
- I also tried older black versions during my own bug analysis. Version 19.3b0 can be installed somehow. New versions don't.

**Comment by ichard26** [comment]
Do you have `log.showSignature` enabled globally for Git? That's my first guess at where that line would come from.

**Comment by imor-de** [comment]
Thanks! That totally worked. :)
