### ISSUE TITLE
Does not work on Apple Silicon

### ISSUE THREAD

**Issue by muuvmuuv** [psf/black#2077]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Install with pip

**Expected behavior** 

Just work

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: macOS 11.2.3 (20D91)
- Python: 3.9.x

**Does this bug also happen on master?** To answer this, you have two options:

Ran on my machine resulted in:

`pip install -e .`:

```
Obtaining file:///Users/marvin/Downloads/black-test
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pathspec<1,>=0.6 in /Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages (from black==20.8b2.dev118+gc702588) (0.8.1)
Requirement already satisfied: regex>=2020.1.8 in /Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages (from black==20.8b2.dev118+gc702588) (2021.3.17)
Requirement already satisfied: appdirs in /Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages (from black==20.8b2.dev118+gc702588) (1.4.4)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages (from black==20.8b2.dev118+gc702588) (0.4.3)
Requirement already satisfied: toml>=0.10.1 in /Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages (from black==20.8b2.dev118+gc702588) (0.10.2)
Requirement already satisfied: click>=7.1.2 in /Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages (from black==20.8b2.dev118+gc702588) (7.1.2)
Requirement already satisfied: typed-ast>=1.4.2 in /Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages (from black==20.8b2.dev118+gc702588) (1.4.2)
Installing collected packages: black
  Attempting uninstall: black
    Found existing installation: black 20.8b2.dev118+gc702588
    Uninstalling black-20.8b2.dev118+gc702588:
      Successfully uninstalled black-20.8b2.dev118+gc702588
  Running setup.py develop for black
Successfully installed black
```

`python -m unittest`:

```
EEE....[2021-03-31 14:23:30,423] DEBUG: Using selector: KqueueSelector (selector_events.py:59)
.[2021-03-31 14:23:30,424] DEBUG: Using selector: KqueueSelector (selector_events.py:59)
E[2021-03-31 14:23:30,790] DEBUG: Using selector: KqueueSelector (selector_events.py:59)
.[2021-03-31 14:23:30,790] DEBUG: Using selector: KqueueSelector (selector_events.py:59)
[2021-03-31 14:23:30,791] INFO: 17 projects to run Black over (lib.py:316)
[2021-03-31 14:23:30,791] DEBUG: Using 2 parallel workers to run Black (lib.py:321)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on aioexabgp (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on attrs (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on bandersnatch (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on channels (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on django (lib.py:252)
[2021-03-31 14:23:30,791] INFO: Skipping django as it's disabled via config (lib.py:259)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on flake8-bugbear (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on hypothesis (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on pandas (lib.py:252)
[2021-03-31 14:23:30,791] INFO: Skipping pandas as it's disabled via config (lib.py:259)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on pillow (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on poetry (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on ptr (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on pyramid (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on pytest (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on sqlalchemy (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on tox (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on virtualenv (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: worker 0 working on warehouse (lib.py:252)
[2021-03-31 14:23:30,791] DEBUG: project_runner 0 exiting (lib.py:250)
[2021-03-31 14:23:30,791] DEBUG: project_runner 1 exiting (lib.py:250)
[2021-03-31 14:23:30,791] INFO: Analyzing results (lib.py:332)
.
======================================================================
ERROR: tests.test_black (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_black
Traceback (most recent call last):
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/marvin/Downloads/black-test/tests/test_black.py", line 13, in <module>
    import regex as re
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture


======================================================================
ERROR: tests.test_blackd (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_blackd
Traceback (most recent call last):
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/marvin/Downloads/black-test/tests/test_blackd.py", line 7, in <module>
    from tests.util import read_data, DETERMINISTIC_HEADER, skip_if_exception
  File "/Users/marvin/Downloads/black-test/tests/util.py", line 6, in <module>
    import black
  File "/Users/marvin/Downloads/black-test/src/black/__init__.py", line 17, in <module>
    import regex as re
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture


======================================================================
ERROR: tests.test_format (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_format
Traceback (most recent call last):
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/marvin/Downloads/black-test/tests/test_format.py", line 3, in <module>
    import black
  File "/Users/marvin/Downloads/black-test/src/black/__init__.py", line 17, in <module>
    import regex as re
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/marvin/.pyenv/versions/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture


======================================================================
ERROR: test_gen_check_output (tests.test_primer.PrimerLibTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/marvin/Downloads/black-test/tests/test_primer.py", line 143, in test_gen_check_output
    stdout, stderr = loop.run_until_complete(
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/marvin/Downloads/black-test/src/black_primer/lib.py", line 68, in _gen_check_output
    raise CalledProcessError(
subprocess.CalledProcessError: Command 'black --help' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 11 tests in 0.371s

FAILED (errors=4)
```

`black --version`:

```
Traceback (most recent call last):
  File "/Users/marvin/.pyenv/versions/black-test/bin/black", line 33, in <module>
    sys.exit(load_entry_point('black', 'console_scripts', 'black')())
  File "/Users/marvin/.pyenv/versions/black-test/bin/black", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/marvin/.pyenv/versions/3.9.2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/marvin/Downloads/black-test/src/black/__init__.py", line 17, in <module>
    import regex as re
  File "/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/marvin/.pyenv/versions/3.9.2/envs/black-test/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by cooperlees** [comment]
I’m getting a M1 in the next few days. I’ll see what I can do, but if you install regex module from source I feel it will work. It’s our main compiled dependency.

**Comment by muuvmuuv** [comment]
Never tried the "regex" package but why isn't the default "re" package enough, what are the benefits from "regex"?

**Comment by JelleZijlstra** [comment]
Better unicode support, though if I recall correctly this only comes up in some pretty obscure cases. If you patch Black to use `re` directly it will probably mostly work.

**Comment by JelleZijlstra** [comment]
#455

**Comment by muuvmuuv** [comment]
I tried but could not get it working locally. Wonder if after two years it might be obsolete and be removed?

**Comment by muuvmuuv** [comment]
Yes it seems to be gone on my machine too. Idk what caused this, maybe a failed dependency SHA from an old cache.

**Comment by cooperlees** [comment]
So lets read the error you have there. This is not black at all but a dependency, `regex`. It's a C extension, so has to be compiled for each CPU architecture and platform. You somehow have a non arm64 version:
```
/Users/smirnoffs/dev/shortme/.venv/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
```

So please get a arm64 regex into your environment. Maybe try `pip uninstall regex ; pip install regex`

Did you port this venv from another Mac? Download a already made venv or old version of regex that does not have an `arm64` wheel?

**Comment by cooperlees** [comment]
Tested again for prosperity:

```console
crl-m1:~ cooper$ uname -a
Darwin crl-m1.cooperlees.com 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64

crl-m1:~ cooper$ python3 -V
Python 3.9.5

crl-m1:~ cooper$ python3 -m venv --upgrade-deps /tmp/tb
Requirement already satisfied: pip in /private/tmp/tb/lib/python3.9/site-packages (21.1.1)
Requirement already satisfied: setuptools in /private/tmp/tb/lib/python3.9/site-packages (56.0.0)
Collecting setuptools
  Using cached setuptools-56.2.0-py3-none-any.whl (785 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed setuptools-56.2.0
crl-m1:~ cooper$ /tmp/tb/bin/pip install black
Collecting black
  Downloading black-21.5b1-py3-none-any.whl (137 kB)
     |████████████████████████████████| 137 kB 911 kB/s
Collecting click>=7.1.2
  Downloading click-8.0.0-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 6.4 MB/s
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting regex>=2020.1.8
  Using cached regex-2021.4.4-cp39-cp39-macosx_11_0_arm64.whl
Collecting toml>=0.10.1
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pathspec<1,>=0.8.1
  Using cached pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Installing collected packages: toml, regex, pathspec, mypy-extensions, click, appdirs, black
Successfully installed appdirs-1.4.4 black-21.5b1 click-8.0.0 mypy-extensions-0.4.3 pathspec-0.8.1 regex-2021.4.4 toml-0.10.2

crl-m1:~ cooper$ /tmp/tb/bin/black ~/repos/black/setup.py
All done! ✨ 🍰 ✨
1 file left unchanged.
```

Key line there:   Using cached regex-2021.4.4-cp39-cp39-macosx_11_0_arm64.whl

All works on 3.9.5 for me with latest version of everything.

**Comment by smirnoffs** [comment]
Thanks for checking @cooperlees. I checked the architecture and it is exactly the same as yours `root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64`. The virtual env is freshly created, I tried with different pythons installed from brew, pyenv and the official installer. I also tried to reinstall `regex`. The result is always the same
```
ImportError: dlopen(/private/tmp/blck/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/private/tmp/blck/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
	/private/tmp/blck/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: mach-o, but wrong architecture
```
Obviously everything works under Rosetta without issues. Maybe I did something wrong, cannot find the trace of the wrong step though.

**Comment by naanadr** [comment]
I have the same problem with Python 3.9.5 😢

**Comment by cooperlees** [comment]
> I have the same problem with Python 3.9.5

Can we get some more info here please. What are you doing differently to my venv from scratch example above (https://github.com/psf/black/issues/2077#issuecomment-839207189)?

**Comment by naanadr** [comment]
Hi @cooperlees.

I installed the python versions with `pyenv` and installed `black` with `pip` . 
Black only works here (my Mac is a Big Sur with M1) in `3.8.x` .

**Comment by seungha-kim** [comment]
I've solved by installing intel-only Python.. but it doesn't seems the best solution.
