### ISSUE TITLE
Primer: Fix RuntimeError with a closed Event Loop with subprocesses

### ISSUE THREAD

**Issue by cooperlees** [psf/black#2193]
From time to time it seems `pandas` causes an EventLoop `RuntimeError` error.

Let's debug and see if there is something we're not cleaning up / waiting for with subprocesses to catch this and exit cleanly / handle the issue.

- Example fail run: https://github.com/psf/black/runs/2503011226

Seen in both 3.6 and 3.9 the most.

```
-- primer results 📊 --
[2021-05-04 18:14:53,570] INFO: Analyzing results (lib.py:356)

17 / 19 succeeded (89.47%) ✅
2 / 19 FAILED (10.53%) 💩
 - 1 project disabled by config
 - 0 projects skipped due to Python version
 - 0 skipped due to long checkout

Failed projects:

## pandas:
 - Returned 0
 - stdout:
Expected formatting changes but didn't get any!

Exception ignored in: <bound method BaseSubprocessTransport.__del__ of <_UnixSubprocessTransport closed pid=2174 returncode=-9 stdout=<_UnixReadPipeTransport closing fd=6 open>>>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_subprocess.py", line 132, in __del__
    self.close()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_subprocess.py", line 106, in close
    proto.pipe.close()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/unix_events.py", line 423, in close
    self._close(None)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/unix_events.py", line 452, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 595, in call_soon
    self._check_closed()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/asyncio/base_events.py", line 381, in _check_closed
Error:     raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Error: Process completed with exit code 2.
```

If anyone has seen this PRs welcome!

**Comment by cooperlees** [comment]
O, second look, it seems we expect formatting change but don't get any ... Wonder why not all primer fails then.

**Comment by felix-hilden** [comment]
Just so that this doesn't get buried after we deprecate primer, if it's still worth fixing #2821
