### ISSUE TITLE
21.5b1: cannot generate man page

### ISSUE THREAD

**Issue by kloczek** [psf/black#2241]
After `setup.py build`:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/black-21.5b1/build/lib
+ sphinx-build -b man -d black docs .
Running Sphinx v3.5.4

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/home/tkloczko/rpmbuild/BUILD/black-21.5b1/docs/conf.py", line 40, in <module>
    release = get_distribution("black").version.split("+")[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'black' distribution was not found and is required by the application
```

**Comment by ichard26** [comment]
Hi,

It appears that your environment doesn't have Black installed. Why does our docs need a Black installation? Some of our documentation is generated from the Black source code (mostly automatic API / CLI documentation).

Using my local development for Black, I can create the man page just fine. 

```console
~/programming/oss/black/docs on main [$?⇡] via v3.8.5 (black) 
❯ sphinx-build -b man . _build/man -d _build/doctrees/ -v
Running Sphinx v3.5.4
Adding copy buttons to code blocks...
loading pickled environment... done
myst v0.13.7: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['dollarmath'], disable_syntax=['myst_block_break', 'myst_line_comment', 'math_block'], url_schemes=None, heading_anchors=3, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'])
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [config changed ('release')] 28 added, 0 changed, 0 removed
reading sources... [  3%] authors
reading sources... [  7%] change_log
reading sources... [ 10%] contributing/gauging_changes
reading sources... [ 14%] contributing/index
reading sources... [ 17%] contributing/issue_triage
reading sources... [ 21%] contributing/reference/reference_classes
reading sources... [ 25%] contributing/reference/reference_exceptions
reading sources... [ 28%] contributing/reference/reference_functions
reading sources... [ 32%] contributing/reference/reference_summary
reading sources... [ 35%] contributing/release_process
reading sources... [ 39%] contributing/the_basics
reading sources... [ 42%] getting_started
reading sources... [ 46%] guides/index
reading sources... [ 50%] guides/introducing_black_to_your_project
reading sources... [ 53%] guides/using_black_with_other_tools
reading sources... [ 57%] index
reading sources... [ 60%] integrations/editors
reading sources... [ 64%] integrations/github_actions
reading sources... [ 67%] integrations/index
reading sources... [ 71%] integrations/source_version_control
reading sources... [ 75%] license
reading sources... [ 78%] the_black_code_style/current_style
reading sources... [ 82%] the_black_code_style/future_style
reading sources... [ 85%] the_black_code_style/index
reading sources... [ 89%] usage_and_configuration/black_as_a_server
reading sources... [ 92%] usage_and_configuration/file_collection_and_discovery
reading sources... [ 96%] usage_and_configuration/index
reading sources... [100%] usage_and_configuration/the_basics

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... black.1 { the_black_code_style/index the_black_code_style/current_style the_black_code_style/future_style getting_started usage_and_configuration/index usage_and_configuration/the_basics usage_and_configuration/file_collection_and_discovery usage_and_configuration/black_as_a_server integrations/index integrations/editors integrations/github_actions integrations/source_version_control guides/index guides/introducing_black_to_your_project guides/using_black_with_other_tools contributing/index contributing/the_basics contributing/gauging_changes contributing/issue_triage contributing/release_process contributing/reference/reference_summary contributing/reference/reference_classes contributing/reference/reference_functions contributing/reference/reference_exceptions change_log authors } done
build succeeded.

The manual pages are in _build/man.

~/programming/oss/black/docs on main [$?⇡] via v3.8.5 (black) took 6s731ms 
❯ lexa _build/man
drwxrwxr-x    - ichard26 ichard26 17 May  8:21 .doctrees
.rw-rw-r-- 164k ichard26 ichard26 17 May 16:48 black.1

~/programming/oss/black/docs on main [$?⇡] via v3.8.5 (black) 
❯ man ./_build/man/black.1  # <-- this works just fine!
```

I hope that helps! Thanks for the reminder for us to provide man page downloads of our docs.

**Comment by ichard26** [comment]
@kloczek can you confirm your issue has been resolved or do you need more help?

(FYI to everyone else: I'll be closing this if I don't get a response in roughly 5 days)

**Comment by kloczek** [comment]
> It appears that your environment doesn't have Black installed

Of course because it is about building black :)

> ❯ sphinx-build -b man . _build/man -d _build/doctrees/ -v

OK so how `_build/` directory should appear? `python3 setup.py build` does not generate anything in `_build/` but in  `build/` and after that there is no `build/man`
```console
[tkloczko@barrel black-21.5b1]$ python3 setup.py --help-commands | egrep "man|doc"
Standard commands:
  clean             clean up temporary files from 'build' command
Extra commands:
  build_sphinx      Build Sphinx documentation
  alias             define a shortcut to invoke one or more commands
  upload_docs       Upload documentation to PyPI
   or: setup.py --help-commands

[tkloczko@barrel black-21.5b1]$ PYTHONPATH=${PWD}/build/lib python3 setup.py build_sphinx
running build_sphinx
Running Sphinx v4.0.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/black-21.5b1/docs/conf.py", line 40, in <module>
    release = get_distribution("black").version.split("+")[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'black' distribution was not found and is required by the application

[tkloczko@barrel black-21.5b1]$ ls -l build/lib/
total 4
drwxr-xr-x 1 tkloczko tkloczko 392 May 24 20:19 black
drwxr-xr-x 1 tkloczko tkloczko  22 May 24 20:19 blackd
drwxr-xr-x 1 tkloczko tkloczko  46 May 24 20:19 black_primer
-rw-r--r-- 1 tkloczko tkloczko  19 May 24 20:19 _black_version.py
drwxr-xr-x 1 tkloczko tkloczko 126 May 24 20:19 blib2to3
```

**Comment by felix-hilden** [comment]
I think there is a confusion about building and installing Black itself vs. building documentation. It appears you are trying to build documentation, for which Black needs to already be installed.

Could you follow the installation part of the [contributing guide](https://black.readthedocs.io/en/stable/contributing/the_basics.html) and then try to build the documentation as you already tried?

**Comment by kloczek** [comment]
That link does not provide any instructions/hints about how to **build** black and its documentation as roff man page(s). It focuses on many other aspects which I don't want to reproduce because I'm packaging black and other python modules as rpm packages.
So again: how to **build** black and its documentation?

**Comment by ichard26** [comment]
The TL;DR is that you need the Black you are building (which btw I don't really understand what you mean by that) installed so the documentation can be built.

If you really want to use `python setup.py build_sphinx` over the more common and modern `sphinx-build` command then here's how:

1. Get a Python environment
2. Install a version of Black in said environment (probably your local cloned copy so `pip install .[d]` - note you'll need the `d` extra)
3. Run `python setup.py build_sphinx -b man`

**Comment by kloczek** [comment]
> Run python setup.py build_sphinx -b man

That command does not work without installing black. Issue is that I'm completting build procedurew which is used to generate rpm package. Chicken and egg prolem ..
```console
[tkloczko@barrel black-21.5b1]$ /usr/bin/python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/black-21.5b1/docs/conf.py", line 40, in <module>
    release = get_distribution("black").version.split("+")[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'black' distribution was not found and is required by the application
```

**Comment by kloczek** [comment]
Quick search and looks like `src_paths = []` is missing in conf.py.
https://github.com/sphinx-doc/sphinx/issues/3132

**Comment by kloczek** [comment]
Just tested new 21.7b0 version.
All looks clean now.
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.3
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
myst v0.15.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=['myst_block_break', 'myst_line_comment', 'math_block'], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=3, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 29 added, 0 changed, 0 removed
reading sources... [100%] usage_and_configuration/the_basics
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-black.3 { the_black_code_style/index the_black_code_style/current_style the_black_code_style/future_style getting_started usage_and_configuration/index usage_and_configuration/the_basics usage_and_configuration/file_collection_and_discovery usage_and_configuration/black_as_a_server integrations/index integrations/editors integrations/github_actions integrations/source_version_control guides/index guides/introducing_black_to_your_project guides/using_black_with_other_tools faq contributing/index contributing/the_basics contributing/gauging_changes contributing/issue_triage contributing/release_process contributing/reference/reference_summary contributing/reference/reference_classes contributing/reference/reference_functions contributing/reference/reference_exceptions change_log authors } done
build succeeded.
```
Thank you :)
Closing.
