### ISSUE TITLE
Having a file "numbers.py" breaks black

### ISSUE THREAD

**Issue by lucasfcnunes** [psf/black#2347]
**Describe the bug**

Python files in vscode project influence black (modules importing) causing errors.

**Environment**

- Ubuntu 20.04
- vscode 1.57.1      commit 507ce72a4...
- conda 4.10.1
- python                    3.9.5           h49503c6_0_cpython    conda-forge (`~/miniconda3/envs/py39/bin/python` my conda env for following references)
- black                     21.5b2             pyhd8ed1ab_0    conda-forge
or
- black                     21.6b0                   pypi_0    pypi (>"Does this bug also happen on main?" )

**To Reproduce**

- .vscode/settings.json has line: `"python.formatting.provider": "black",`
- create a file called `numbers.py` (the content don't matter)
- Use "Format Document" in F1 or save (when "format on save" is true) to format any other .py files
- File will not format.
- Rename `numbers.py` to, literally, anything else: issue is gone.

"Python output" on vscode:
`~/miniconda3/envs/py39/bin/python -m black --diff --quiet <file>.py`

Manually running the above on terminal (pwd is same path as `numbers.py`):
```sh
$ ~/miniconda3/envs/py39/bin/python -m black --diff --quiet dictionaries.py                                                                                                                                                (py39) 
Traceback (most recent call last):
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/site-packages/black/__init__.py", line 44, in <module>
    from black.files import find_project_root, find_pyproject_toml, parse_pyproject_toml
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/site-packages/black/files.py", line 21, in <module>
    import toml
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/site-packages/toml/__init__.py", line 6, in <module>
    from toml import encoder
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/site-packages/toml/encoder.py", line 4, in <module>
    from decimal import Decimal
  File "/home/lucasfcnunes/miniconda3/envs/py39/lib/python3.9/decimal.py", line 3, in <module>
    from _decimal import *
AttributeError: module 'numbers' has no attribute 'Number'
```

**Expected behavior**

Format normally. Ignoring project files.
*Maybe this issue is greater than black itself... idk ^^

**Does this bug also happen on main?**

Yes. black 21.6b0 pypi too.

**Additional context**

BREAKING NEWS: **TwillioQuest** breaks black formater.

**Comment by JelleZijlstra** [comment]
This is a general issue with Python importing: if there's something on your path that shadows a standard library module, bad things happen. You'll get similar issues with files named `decimal.py` or `toml.py`, just looking at the stack trace.

I don't think this is fixable in Black.
