### ISSUE TITLE
regression with path traversals in 21.5b2

### ISSUE THREAD

**Issue by pLeBlanc93** [psf/black#2389]
**Describe the bug**

```py
Traceback (most recent call last):
  File "C:\python\conda\envs\clone\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python\conda\envs\clone\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python\conda\envs\clone\Scripts\black.exe\__main__.py", line 7, in <module>
  File "C:\python\conda\envs\clone\lib\site-packages\black\__init__.py", line 1130, in patched_main
    main()
  File "C:\python\conda\envs\clone\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\python\conda\envs\clone\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\python\conda\envs\clone\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python\conda\envs\clone\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\python\conda\envs\clone\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\python\conda\envs\clone\lib\site-packages\black\__init__.py", line 421, in main
    stdin_filename=stdin_filename,
  File "C:\python\conda\envs\clone\lib\site-packages\black\__init__.py", line 518, in get_sources
    gitignore,
  File "C:\python\conda\envs\clone\lib\site-packages\black\files.py", line 223, in gen_python_files
    gitignore + get_gitignore(child) if gitignore is not None else None,
TypeError: unsupported operand type(s) for +: 'PathSpec' and 'PathSpec'
```

It looks like this was introduced with https://github.com/psf/black/commit/b8450b9faee10f3a0a63378b58adde60a27964e0#diff-1a5882c84fe4b3f18199a3e021822c1ea4bdc3f86952ea450c4db15d9387c7c3L215

**To Reproduce**

1. Create a local folder `black_test` that has a file `foo.py` and an empty folder `bar`
2. `black C:/temp/black_test`

**Expected behavior**
This works with `black 21.5b1`

**Environment (please complete the following information):**

- Version:  21.5b2
- OS and Python version:  Windows/Python 3.7.10 x64

**Does this bug also happen on main?**

Haven't tested main yet, but it's also present on 21.7b0

**Additional context**

**Comment by ichard26** [comment]
Hey thanks for the bug report! This isn't actually a bug with Black itself, the problem lies in pathspec. I'm not entirely sure how you managed to get a pathspec that isn't 0.8.1 or higher since version 21.4b1 (containing this commit: https://github.com/psf/black/commit/a0b4e609a7393fac11ecc94eb859c1e85b540036) bumped Black's minimum pathspec requirement: https://github.com/psf/black/blob/1728bb441e6cc3ba5a5ce52ec62014bbfa435a82/setup.py#L75-L77

Why 0.8.1 specifically? It's the version that added addition support to `PathSpec` objects (see https://github.com/cpburnz/python-path-specification/pull/43).

**Comment by pLeBlanc93** [comment]
Ahh, that explains it. Thanks for quick response!

I also do not understand why `pip install "black==21.7b0"` did not upgrade pathspec. But confirmed that manually upgrading pathspec makes this issue non-repro. How interesting...

**Comment by bashtage** [comment]
Recent black requires pathspec>=0.9.0 (as indicated in setup.py) which was also not automatically installed for me when installing black.
