### ISSUE TITLE
pre-commit hook causes error: Type tag 'jupyter' is not recognized.

### ISSUE THREAD

**Issue by inhumantsar** [psf/black#2505]
**Describe the bug**

When using only the `black` pre-commit hook using the default install (ie: not `black[jupyter]`), pre-commit throws the following error:

```
An error has occurred: InvalidManifestError: 
==> File /Users/sam/.cache/pre-commit/repox0xprpud/.pre-commit-hooks.yaml
==> At Hook(id='black-jupyter')
==> At key: types_or
==> At index 2
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?
```

Downgrading the pre-commit hook to 21.7b0 works as expected.

**To Reproduce**

* Install pre-commit 2.15.0
* Configure the black hook as in docs:

```
repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
```
* `pre-commit install`
* `git commit ...`

**Expected behavior**

No error

**Environment (please complete the following information):**

- Version: 21.9b0
- OS and Python version: OSX 11.2.3 Python 3.8.2 (venv)
```
❯ pip freeze | grep -e 'pre-commit\|identify\|black'
black==21.9b0
identify==1.4.14
pre-commit==2.15.0
```

**Additional context**

Pre-commit logs:

### version information

```
pre-commit version: 2.15.0
sys.version:
    3.8.2 (default, Apr  8 2021, 23:19:18) 
    [Clang 12.0.5 (clang-1205.0.22.9)]
sys.executable: ...snip.../venv/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: InvalidManifestError: 
==> File /Users/sam/.cache/pre-commit/repox0xprpud/.pre-commit-hooks.yaml
==> At Hook(id='black-jupyter')
==> At key: types_or
==> At index 2
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?
```

```
Traceback (most recent call last):
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/clientlib.py", line 30, in check_type_tag
    raise cfgv.ValidationError(
cfgv.ValidationError: 
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/clientlib.py", line 30, in check_type_tag
    raise cfgv.ValidationError(
cfgv.ValidationError: 
==> At index 2
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/clientlib.py", line 30, in check_type_tag
    raise cfgv.ValidationError(
cfgv.ValidationError: 
==> At key: types_or
==> At index 2
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/clientlib.py", line 30, in check_type_tag
    raise cfgv.ValidationError(
cfgv.ValidationError: 
==> At Hook(id='black-jupyter')
==> At key: types_or
==> At index 2
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/clientlib.py", line 30, in check_type_tag
    raise cfgv.ValidationError(
cfgv.ValidationError: 
==> File /Users/sam/.cache/pre-commit/repox0xprpud/.pre-commit-hooks.yaml
==> At Hook(id='black-jupyter')
==> At key: types_or
==> At index 2
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/main.py", line 368, in main
    return hook_impl(
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 404, in run
    for hook in all_hooks(config, store)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/repository.py", line 228, in all_hooks
    return tuple(
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/repository.py", line 173, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "...snip.../venv/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "...snip.../venv/lib/python3.8/site-packages/pre_commit/clientlib.py", line 30, in check_type_tag
    raise cfgv.ValidationError(
pre_commit.clientlib.InvalidManifestError: 
==> File /Users/sam/.cache/pre-commit/repox0xprpud/.pre-commit-hooks.yaml
==> At Hook(id='black-jupyter')
==> At key: types_or
==> At index 2
=====> Type tag 'jupyter' is not recognized.  Try upgrading identify and pre-commit?
```

**Comment by MarcoGorelli** [comment]
Can you try updating your version of identify?

**Comment by tritas** [comment]
Can reproduce with ``identify=2.2.15``

**Comment by felix-hilden** [comment]
Thanks @tritas for confirming. I'll also link to pre-commit/pre-commit#1946, where an option for a minimum `identify` version was discussed, but it was rejected. So we'll have to make do with manually upgrading. Thankfully the message is quite clear.
