### ISSUE TITLE
Pattern matching won't format with 21.11b1 (lib2to3_parse error)

### ISSUE THREAD

**Issue by fredrikaverpil** [psf/black#2625]
**Describe the bug**

Cannot format file with pattern in it 😭 

**To Reproduce**

Take this code:

```python
class I:
    def __init__(self, type_, val=None):
        self.type = type_
        self.val = val


instances = [I(type_="image"), I(type_="video")]


for instance in instances:
    match instance.type:
        case "image":
            print("hello image")

        case "video":
            print("hello video")

```

And run it with these arguments:

```sh
$ black --version
black, 21.11b1 (compiled: no)

$ black py310test.py -v
```

The resulting error is:

```
Using configuration from /home/fredrik/code/repos/temp/pyproject.toml.
Traceback (most recent call last):
  File "/home/fredrik/code/repos/temp/.venv/lib/python3.10/site-packages/black/__init__.py", line 654, in reformat_one
    if changed is not Changed.CACHED and format_file_in_place(
  File "/home/fredrik/code/repos/temp/.venv/lib/python3.10/site-packages/black/__init__.py", line 811, in format_file_in_place
    dst_contents = format_file_contents(src_contents, fast=fast, mode=mode)
  File "/home/fredrik/code/repos/temp/.venv/lib/python3.10/site-packages/black/__init__.py", line 935, in format_file_contents
    dst_contents = format_str(src_contents, mode=mode)
  File "/home/fredrik/code/repos/temp/.venv/lib/python3.10/site-packages/black/__init__.py", line 1072, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/home/fredrik/code/repos/temp/.venv/lib/python3.10/site-packages/black/parsing.py", line 111, in lib2to3_parse
    raise exc from None
black.parsing.InvalidInput: Cannot parse: 11:10:     match instance.type:
error: cannot format py310test.py: Cannot parse: 11:10:     match instance.type:
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior**

Well, not a crash!

**Environment**

```
❯ poetry show black   
name         : black
version      : 21.11b1
description  : The uncompromising code formatter.

dependencies
 - click >=7.1.2
 - mypy-extensions >=0.4.3
 - pathspec >=0.9.0,<1
 - platformdirs >=2
 - regex >=2021.4.4
 - tomli >=0.2.6,<2.0.0
 - typing-extensions >=3.10.0.0
 - typing-extensions !=3.10.0.1
```

EDIT: I also tried this in a brand new venv with the same result:

```bash
❯ pip list         
Package           Version
----------------- ----------
black             21.11b1
click             8.0.3
mypy-extensions   0.4.3
pathspec          0.9.0
pip               21.2.3
platformdirs      2.4.0
regex             2021.11.10
setuptools        57.4.0
tomli             1.2.2
typing_extensions 4.0.0
```

- OS: Ubuntu 20.0.4 LTS running under WSL2 in Windows 10
- Python: 3.10.0 64-bit

**Additional context**

😭

**Comment by ichard26** [comment]
Did you pass --target-version py310 to Black?

**Comment by fredrikaverpil** [comment]
No I did not pass this argument to black. When I do that, formatting works for this example! 👍 
Many, many thanks.

**Comment by fredrikaverpil** [comment]
@ichard26 for the command line, it works:

```bash
```

**Comment by fredrikaverpil** [comment]
@ichard26 for the command line, it works:

```bash
black --target-version py310 py310test.py
```

But not when relying on pyproject.toml:

```toml
target-version = ['py310']
```

Is this a known problem or am I doing something wrong?
