### ISSUE TITLE
black crashes when it cannot determine home directory

### ISSUE THREAD

**Issue by ewjoachim** [psf/black#2813]
**Describe the bug**

If the user launching black doesn't have a home directory, black crashes

**To Reproduce**

```console
$ docker run -u 1234 --rm -it python bash
$ I have no name!@9e8b6938d741:/$ python -m venv /tmp/venv
$ I have no name!@9e8b6938d741:/$ /tmp/venv/bin/python -m pip install black
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting black
[...]
Installing collected packages: typing-extensions, tomli, platformdirs, pathspec, mypy-extensions, click, black
Successfully installed black-21.12b0 click-8.0.3 mypy-extensions-0.4.3 pathspec-0.9.0 platformdirs-2.4.1 tomli-1.2.3 typing-extensions-4.0.1
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/tmp/venv/bin/python -m pip install --upgrade pip' command.
$ I have no name!@9e8b6938d741:/$ unset HOME
$ I have no name!@9e8b6938d741:/$ /tmp/venv/bin/python -m black /tmp
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/venv/lib/python3.10/site-packages/black/__main__.py", line 3, in <module>
    patched_main()
  File "/tmp/venv/lib/python3.10/site-packages/black/__init__.py", line 1373, in patched_main
    main()
  File "/tmp/venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/venv/lib/python3.10/site-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/tmp/venv/lib/python3.10/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/tmp/venv/lib/python3.10/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/tmp/venv/lib/python3.10/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/tmp/venv/lib/python3.10/site-packages/click/core.py", line 2309, in process_value
    value = self.callback(ctx, self, value)
  File "/tmp/venv/lib/python3.10/site-packages/black/__init__.py", line 114, in read_pyproject_toml
    value = find_pyproject_toml(ctx.params.get("src", ()))
  File "/tmp/venv/lib/python3.10/site-packages/black/files.py", line 80, in find_pyproject_toml
    path_user_pyproject_toml = find_user_pyproject_toml()
  File "/tmp/venv/lib/python3.10/site-packages/black/files.py", line 116, in find_user_pyproject_toml
    user_config_path = Path(config_root).expanduser() / "black"
  File "/usr/local/lib/python3.10/pathlib.py", line 1438, in expanduser
    raise RuntimeError("Could not determine home directory.")
RuntimeError: Could not determine home directory.
```

**Expected behavior**

Either black should issue a warning saying it couldn't search the home directory for configuration (I think it's the best solution), or it should just silently ignore the error.

**Environment**

- Black's version: 21.12b0
- OS and Python version: Debian 11 / Python 3.10

**Additional context**

I understand if you consider that a setup where the user doesn't have a home is broken and you don't intend on supporting it. This failed in my Jenkins CI, where the docker setup forces the inner docker user to have the same UID as the outer jenkins user, ending up using a user that doesn't exist on the docker instance, which runs most tools without issues, but fails with black.

I'll try to do a PR :)

**Comment by felix-hilden** [comment]
Thanks for reporting this! And a PR is very much welcome 😃
