### ISSUE TITLE
black fails due to _unicodefun

### ISSUE THREAD

**Issue by NAThompson** [psf/black#2963]
**Describe the bug**

On Centos 7:

```
WARNING: You are using pip version 21.2.3; however, version 22.0.4 is available.
$ python3.9 -m venv venv
$ source venv/bin/activate.csh
(venv) $ python3 -m pip install black
(venv) $ black --version
black, 22.1.0 (compiled: yes) 
(venv) $ black . --check --diff --color
Traceback (most recent call last):
  File "~/venv/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (~/venv/lib/python3.9/site-packages/click/__init__.py)
```

**Additional context**

This just popped up today in CI; it was not observed earlier. Maybe the dependencies are not tightly pinned?

**Comment by Sillocan** [comment]
Yep. Click 8.1.0 was released with a breaking change.

**Comment by JelleZijlstra** [comment]
Going to close in favor of #2964 which is now pinned.
