### ISSUE TITLE
Still getting `ImportError: cannot import name '_unicodefun' from 'click'` with `=black-22.3.0`

### ISSUE THREAD

**Issue by TheChymera** [psf/black#2984]
I have alternatively tried downgrading either black, click, or both, and the following issue still persists:

```console
chymera@decohost ~/src/dandi-cli/dandi/tests $ git commit .
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for added large files..............................................Passed
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/chymera/.cache/pre-commit/repok5kxcu1f/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/chymera/.cache/pre-commit/repok5kxcu1f/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 1065, in patched_main
    patch_click()
  File "/home/chymera/.cache/pre-commit/repok5kxcu1f/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 1052, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/chymera/.cache/pre-commit/repok5kxcu1f/py_env-python3/lib/python3.9/site-packages/click/__init__.py)

isort....................................................................Passed
codespell................................................................Passed
flake8...................................................................Passed
chymera@decohost ~/src/dandi-cli/dandi/tests $ eix -e click
[I] dev-python/click
     Available versions:  7.1.2-r1^t 8.0.4^t (~)8.1.0^t (~)8.1.1^t {doc examples test PYTHON_TARGETS="pypy3 python3_8 python3_9 python3_10"}
     Installed versions:  8.1.1^t(15:05:10 31/03/22)(-doc -examples -test PYTHON_TARGETS="python3_9 -pypy3 -python3_8 -python3_10")
     Homepage:            https://palletsprojects.com/p/click/ https://pypi.org/project/click/
     Description:         A Python package for creating beautiful command line interfaces

chymera@decohost ~/src/dandi-cli/dandi/tests $ eix -e click-didyoumean
[I] dev-python/click-didyoumean [1]
     Available versions:  (~)0.2.0^t (~)0.3.0^t {test PYTHON_TARGETS="pypy3 python3_8 python3_9 python3_10"}
     Installed versions:  0.3.0[2](11:16:38 25/03/22)(test PYTHON_TARGETS="python3_9 -pypy3 -python3_8 -python3_10")
     Homepage:            https://github.com/click-contrib/click-didyoumean
     Description:         Enable git-like did-you-mean feature in click

[1] "science" /var/db/repos/science
[2] "chymeric" /home/chymera/src/overlay
chymera@decohost ~/src/dandi-cli/dandi/tests $ eix -e black
[I] dev-python/black
     Available versions:  21.12_beta0^t (~)21.12_beta0-r1^t 22.1.0^t 22.3.0^t {test PYTHON_TARGETS="python3_8 python3_9 python3_10"}
     Installed versions:  22.3.0^t(15:05:56 31/03/22)(-test PYTHON_TARGETS="python3_9 -python3_8 -python3_10")
     Homepage:            https://black.readthedocs.io/en/stable/ https://github.com/psf/black
     Description:         The uncompromising Python code formatter

chymera@decohost ~/src/dandi-cli/dandi/tests $ eix -e pre-commit
[I] dev-vcs/pre-commit
     Available versions:  2.17.0^t {test PYTHON_SINGLE_TARGET="python3_8 python3_9 python3_10"}
     Installed versions:  2.17.0^t(13:34:41 01/02/22)(-test PYTHON_SINGLE_TARGET="python3_9 -python3_8 -python3_10")
     Homepage:            https://pre-commit.com/
     Description:         A framework for managing and maintaining multi-language Git pre-commit hooks
```
 Any ideas what the issue might be? Editing `/home/chymera/.cache/pre-commit/repok5kxcu1f/py_env-python3/lib/python3.9/site-packages/black/__init__.py` to remove the offending import lines "fixed" it for the time being, but that file would be auto-regenereated.

**Comment by jack1142** [comment]
see #2964

**Comment by JelleZijlstra** [comment]
You likely have a cached old version of Black in your pre-commit env. See https://github.com/psf/black/issues/2964#issuecomment-1083591334 for suggested upgrade commands.
