### ISSUE TITLE
ImportError: cannot import name 'NL' from 'blib2to3.pytree'

### ISSUE THREAD

**Issue by CudaText-addons** [psf/black#3099]
I got latest Black from PyPI, and got all latest libs for it.
I got lib2to3 from
https://github.com/python/cpython
and renamed its folder to 'blib2to3'.
now I run CudaText plugin 'Black formatter' and get errors

```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_fmt/__init__.py", line 227, in format
    res = helpers.get_props(lexer)
  File "/home/user/.config/cudatext/py/cuda_fmt/__init__.py", line 148, in get_props
    return self.get_item_props(item)
  File "/home/user/.config/cudatext/py/cuda_fmt/__init__.py", line 128, in get_item_props
    _m = importlib.import_module(helper['module'])
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.config/cudatext/py/cuda_fmt_python_black/__init__.py", line 10, in <module>
    from . import black
  File "/home/user/.config/cudatext/py/cuda_fmt_python_black/black/__init__.py", line 39, in <module>
    from black.const import DEFAULT_LINE_LENGTH, DEFAULT_INCLUDES, DEFAULT_EXCLUDES
  File "/home/user/.config/cudatext/py/cuda_fmt_python_black/black/__init__.py", line 41, in <module>
    from black.nodes import STARS, syms, is_simple_decorator_expression
  File "/home/user/.config/cudatext/py/cuda_fmt_python_black/black/nodes.py", line 29, in <module>
    from blib2to3.pytree import Node, Leaf, type_repr, NL
ImportError: cannot import name 'NL' from 'blib2to3.pytree' (/home/user/.config/cudatext/py/cuda_fmt_python_black/blib2to3/pytree.py)
```

**Comment by CudaText-addons** [comment]
This is testing of CudaText plugin for Black:
![Screenshot from 2022-06-04 11-55-14](https://user-images.githubusercontent.com/17549064/171992179-802f4f9b-bd04-4e03-910a-ff9ca65d0d64.png)

**Comment by zsol** [comment]
This will never work. `blib2to3` is a modified version of `lib2to3`, Black isn't supposed to work with the latter.

**Comment by CudaText-addons** [comment]
Where can I get latest `blib2to3` ?
