### ISSUE TITLE
Attrib error, when I call Black from CudaText on Ubuntu Python 3.8

### ISSUE THREAD

**Issue by CudaText-addons** [psf/black#3102]
I try to update Black in CudaText plugin
https://github.com/cudatext-addons/cuda_fmt_python_black

and now after update of all libs I got this (Ubuntu x64 Python 3.8.10)

```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_fmt/__init__.py", line 227, in format
    res = helpers.get_props(lexer)
  File "/home/user/.config/cudatext/py/cuda_fmt/__init__.py", line 148, in get_props
    return self.get_item_props(item)
  File "/home/user/.config/cudatext/py/cuda_fmt/__init__.py", line 128, in get_item_props
    _m = importlib.import_module(helper['module'])
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.config/cudatext/py/cuda_fmt_python_black/__init__.py", line 14, in <module>
    Ver.PY27,
  File "/usr/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: PY27
ERROR: Exception in CudaText for format: AttributeError: PY27
```

**Comment by JelleZijlstra** [comment]
That looks like a bug in `cuda_fmt_python_black`. We removed version 2.7, but they are still relying on the removed enum value. The bug should be reported to that project instead.

Black makes no guarantees about compatibility when you import its internals.
