### ISSUE TITLE
22.10.0: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [psf/black#3314]
First of all currently it is not possible to use straight `sphinx-build` command to build documentation out of source tree
<details>

```console
+ /usr/bin/sphinx-build -j48 -n -T -b man docs build/sphinx/man
Running Sphinx v5.2.3
/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.17.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/black-22.10.0/docs/conf.py", line 46, in <module>
    release = get_distribution("black").version.split("+")[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'black' distribution was not found and is required by the application

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 274, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 172, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 363, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/black-22.10.0/docs/conf.py", line 46, in <module>
    release = get_distribution("black").version.split("+")[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
```
</details>

This can be fixed by patch like below:
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -15,8 +15,11 @@

 import os
 import string
+import sys
 from pathlib import Path

+sys.path.append(os.path.abspath("../src"))
+
 from pkg_resources import get_distribution

 CURRENT_DIR = Path(__file__).parent
@@ -51,6 +54,9 @@

 make_pypi_svg(release)

+src_paths = [
+    "docs",
+]

 # -- General configuration ---------------------------------------------------
```

This patch fixes what is in the comment and that can of fix is suggested in sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.

<details>

```console
+ /usr/bin/sphinx-build -j48 -n -T -b man docs build/sphinx/man
Running Sphinx v5.2.3
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
myst v0.18.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=[], disable_syntax=['colon_fence', 'myst_block_break', 'myst_line_comment', 'math_block'], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=3, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 30 added, 0 changed, 0 removed
reading sources... [100%] usage_and_configuration/the_basics
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/docs/usage_and_configuration/black_as_a_server.md:26: ERROR: Command ['blackd', '--help'] failed: [Errno 2] No such file or directory: 'blackd'
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/docs/usage_and_configuration/the_basics.md:37: ERROR: Command ['black', '--help'] failed: [Errno 2] No such file or directory: 'black'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-black.3 { the_black_code_style/index the_black_code_style/current_style the_black_code_style/future_style getting_started usage_and_configuration/index usage_and_configuration/the_basics usage_and_configuration/file_collection_and_discovery usage_and_configuration/black_as_a_server usage_and_configuration/black_docker_image integrations/index integrations/editors integrations/github_actions integrations/source_version_control guides/index guides/introducing_black_to_your_project guides/using_black_with_other_tools faq contributing/index contributing/the_basics contributing/gauging_changes contributing/issue_triage contributing/release_process contributing/reference/reference_summary contributing/reference/reference_classes contributing/reference/reference_functions contributing/reference/reference_exceptions change_log authors } /home/tkloczko/rpmbuild/BUILD/black-22.10.0/docs/contributing/reference/reference_classes.rst:8: WARNING: py:class reference target not found: BracketTracker
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.BracketTracker.mark:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.BracketTracker.maybe_increment_for_loop_variable:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.BracketTracker.maybe_decrement_after_for_loop_variable:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.BracketTracker.maybe_increment_lambda_arguments:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.BracketTracker.maybe_decrement_after_lambda_arguments:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.BracketTracker.get_open_lsqb:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.append:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.append:3: WARNING: py:class reference target not found: BracketTracker
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.append_safe:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.has_magic_trailing_comma:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.append_comment:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.comments_after:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.comments_after:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.is_complex_subscript:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.Line.enumerate_with_length:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_default:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_default:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_INDENT:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_DEDENT:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_stmt:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_funcdef:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_match_case:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_suite:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_simple_stmt:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_async_stmt:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_decorators:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_SEMI:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_ENDMARKER:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.LineGenerator.visit_factor:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/docs/contributing/reference/reference_classes.rst:34: WARNING: py:class reference target not found: ProtoComment
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.ProtoComment:3: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/docs/contributing/reference/reference_classes.rst:47: WARNING: py:class reference target not found: Visitor
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.Visitor:1: WARNING: py:obj reference target not found: black.nodes.T
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.Visitor.visit:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.Visitor.visit:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.Visitor.visit:1: WARNING: py:class reference target not found: black.nodes.T
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.Visitor.visit_default:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.Visitor.visit_default:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.Visitor.visit_default:1: WARNING: py:class reference target not found: black.nodes.T
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_empty_tuple:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_empty_tuple:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_import:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_multiline_string:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_one_tuple:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_one_tuple:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.is_split_after_delimiter:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.is_split_after_delimiter:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.is_split_before_delimiter:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.is_split_before_delimiter:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_stub_body:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_stub_body:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_stub_suite:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_vararg:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_yield:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.is_yield:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/concurrency.py:docstring of black.concurrency.schedule_formatting:1: WARNING: py:class reference target not found: asyncio.events.AbstractEventLoop
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/concurrency.py:docstring of black.concurrency.schedule_formatting:1: WARNING: py:class reference target not found: concurrent.futures._base.Executor
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/concurrency.py:docstring of black.concurrency.schedule_formatting:5: WARNING: py:func reference target not found: format_file_in_place
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/files.py:docstring of black.files.gen_python_files:1: WARNING: py:class reference target not found: pathspec.pathspec.PathSpec
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/__init__.py:docstring of black.read_pyproject_toml:1: WARNING: py:class reference target not found: click.core.Context
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/__init__.py:docstring of black.read_pyproject_toml:1: WARNING: py:class reference target not found: click.core.Parameter
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/parsing.py:docstring of black.parsing.lib2to3_parse:1: WARNING: py:class reference target not found: black.mode.TargetVersion
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/parsing.py:docstring of black.parsing.lib2to3_parse:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/parsing.py:docstring of black.parsing.lib2to3_unparse:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.bracket_split_build_line:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.bracket_split_build_line:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.delimiter_split:1: WARNING: py:class reference target not found: black.mode.Feature
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.left_hand_split:1: WARNING: py:class reference target not found: black.mode.Feature
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.right_hand_split:1: WARNING: py:class reference target not found: black.mode.Feature
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.standalone_comment_split:1: WARNING: py:class reference target not found: black.mode.Feature
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.transform_line:1: WARNING: py:class reference target not found: black.mode.Feature
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.child_towards:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.child_towards:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.child_towards:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.child_towards:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.child_towards:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.container_of:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.container_of:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.container_of:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.convert_one_fmt_off_pair:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.dont_increase_indentation:1: WARNING: py:class reference target not found: black.mode.Feature
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.dont_increase_indentation:1: WARNING: py:class reference target not found: black.mode.Feature
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.ensure_visible:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.ensure_visible:3: WARNING: py:func reference target not found: normalize_invisible_parens
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.ensure_visible:3: WARNING: py:func reference target not found: visit_import_from
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.enumerate_reversed:1: WARNING: py:class reference target not found: black.lines.T
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/lines.py:docstring of black.lines.enumerate_reversed:1: WARNING: py:class reference target not found: black.lines.T
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.generate_comments:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.generate_comments:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.generate_comments:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.generate_ignored_nodes:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.generate_ignored_nodes:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.generate_ignored_nodes:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.is_fmt_on:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.is_fmt_on:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.children_contains_fmt_on:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.children_contains_fmt_on:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.first_leaf_of:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.first_leaf_of:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.first_leaf_of:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/__init__.py:docstring of black.get_future_imports:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.maybe_make_parens_invisible_in_atom:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.maybe_make_parens_invisible_in_atom:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.maybe_make_parens_invisible_in_atom:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.maybe_make_parens_invisible_in_atom:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.max_delimiter_priority_in_atom:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/brackets.py:docstring of black.brackets.max_delimiter_priority_in_atom:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/comments.py:docstring of black.comments.normalize_fmt_off:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/numerics.py:docstring of black.numerics.normalize_numeric_literal:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.normalize_prefix:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.normalize_invisible_parens:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.preceding_leaf:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.preceding_leaf:1: WARNING: py:class reference target not found: blib2to3.pytree.Node
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.preceding_leaf:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/linegen.py:docstring of black.linegen.should_split_line:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/concurrency.py:docstring of black.concurrency.shutdown:1: WARNING: py:class reference target not found: asyncio.events.AbstractEventLoop
/home/tkloczko/rpmbuild/BUILD/black-22.10.0/src/black/nodes.py:docstring of black.nodes.whitespace:1: WARNING: py:class reference target not found: blib2to3.pytree.Leaf
done
build succeeded, 120 warnings.
```
</details>
Those warnings are affecting mostly html output (no links only higlited prases)

You can peak on fixes that kind of issues in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/latchset/jwcrypto/pull/289
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/jaraco/cssutils/issues/21
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/frostming/unearth/issues/14
https://github.com/pypa/distlib/commit/98b9b89f

**Comment by kloczek** [comment]
I forgot abot yet anither patch.
Despite moving from `setuptools` to `hatchling` sphinx build still uses `pkg_resources` which part of the `seruptools`
This can be fixed with below patch
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -20,7 +20,7 @@

 sys.path.append(os.path.abspath("../src"))

-from pkg_resources import get_distribution
+from _black_version import version

 CURRENT_DIR = Path(__file__).parent

@@ -46,7 +46,7 @@

 # Autopopulate version
 # The version, including alpha/beta/rc tags, but not commit hash and datestamps
-release = get_distribution("black").version.split("+")[0]
+release = version.split("+")[0]
 # The short X.Y version.
 version = release
 for sp in "abcfr":
```

**Comment by cobaltt7** [comment]
I am able to build without issue, this must have been resolved since.
