### ISSUE TITLE
`# fmt: skip` ignored in fluent interface

### ISSUE THREAD

**Issue by metov** [psf/black#3364]
Say I'd like to format my code like so:
```
v = (
    foo_dict
    .setdefault("a", {})
    .setdefault("b", {})
    .setdefault("c", {})
    .setdefault("d", {})
    .setdefault("e", {})
)
```

Black will of course reformat this to put `foo_dict.setdefault("a", {})` on the first line.

Luckily, there are [directives to not auto-format some lines](doesn’t reformat lines that end with # fmt: skip):

>[black] doesn’t reformat lines that end with # fmt: skip

Yet this doesn't work:

```
v = (
    foo_dict  # fmt: skip
    .setdefault("a", {})
    .setdefault("b", {})
    .setdefault("c", {})
    .setdefault("d", {})
    .setdefault("e", {})
)
```

becomes:
```
v = (
    foo_dict.setdefault("a", {})  # fmt: skip
    .setdefault("b", {})
    .setdefault("c", {})
    .setdefault("d", {})
    .setdefault("e", {})
)
```

Since the line `foo_dict  # fmt: skip` ends with `# fmt: skip`, I would expect black not to reformat it.

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4APGAP9dAD2IimZxl1N_Wg0-FDj_LDYOI4UulvyaSRyhIRD3iE1_UaUsa2tabLgG_7q7ci8kPU2J1QIfgk5RDLYwfkXmPcpq4YYDycB9tn1RzrUjOiVfhqnhzjmMCzoJR2cEPlSD9xP-fJiz0wepDdrTsVdtWMNChg2WYdn-x97ic6830YKslA6qCOjabwKh5KzxHf5c5W42rhyjCS65E9hKQZNO7yF6xbGx_pHlm62FJaocX4NRIyZvchP3oVWj6EK4O1z3xUbh_kuprAlxjK2OQa6PrPGbX1FiLmn04RhIXvw2tECsGAQ88wy6n0Y1eTS8DF7Zh0i1nt8PRmOVp-AjKlWLAAAABa3UZ8yl71cAAZsCxwcAAAeh4SCxxGf7AgAAAAAEWVo=)

**Comment by FSpanhel** [comment]
I also have this issue (see #3443). 

What's the motivation that foo_dict.setdefault("a", {}) is put on the first line? 
The [docs](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#call-chains) only refer to https://en.wikipedia.org/wiki/Fluent_interface.

I had a look on this page. I seems that the majority of languages use 
```
v = (
    foo_dict
    .setdefault("a", {})
    .setdefault("b", {})
    .setdefault("c", {})
    .setdefault("d", {})
    .setdefault("e", {})
)
```
instead of
```
v = (
    foo_dict.setdefault("a", {})
    .setdefault("b", {})
    .setdefault("c", {})
    .setdefault("d", {})
    .setdefault("e", {})
)
```

**Comment by JelleZijlstra** [comment]
Please open a new issue if you want Black's normal formatting to change. This issue should be only about `# fmt: skip` in this context.

**Comment by FSpanhel** [comment]
@JelleZijlstra You are right. My apologies. I have opened #3449.

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Context collection made no progress (located the same files again).

Relevant files:
- src/black/__init__.py: path components match issue terms, source file; bm25 rerank score=42.948; matched issue terms: fmt, skip, ignored, i, d, like; bm25 rerank score=55.042; matched issue terms: fmt, skip, ignored, i, d, like; bm25 rerank score=55.042; matched issue terms: fmt, skip, ignored, i, d, like
- src/black/trans.py: path components match issue terms, source file; bm25 rerank score=30.737; matched issue terms: fmt, skip, i, like, format, my; bm25 rerank score=41.279; matched issue terms: fmt, skip, i, like, format, my; bm25 rerank score=41.279; matched issue terms: fmt, skip, i, like, format, my
- src/black/ranges.py: path components match issue terms, source file; bm25 rerank score=21.337; matched issue terms: fmt, skip, i, like, format, my; bm25 rerank score=25.634; matched issue terms: fmt, skip, i, like, format, my; bm25 rerank score=37.610; matched issue terms: fmt, skip, i, like, format, my; bm25 rerank score=37.610; matched issue terms: fmt, skip, i, like, format, my
- src/black/linegen.py: path components match issue terms, source file; bm25 rerank score=24.016; matched issue terms: fmt, skip, i, like, format, code; bm25 rerank score=25.623; matched issue terms: fmt, skip, i, like, format, code; bm25 rerank score=35.922; matched issue terms: fmt, skip, i, like, format, code; bm25 rerank score=35.922; matched issue terms: fmt, skip, i, like, format, code
- src/black/lines.py: filename appears in issue text, path components match issue terms, source file; bm25 rerank score=21.392; matched issue terms: fmt, skip, ignored, i, like, code; bm25 rerank score=25.178; matched issue terms: fmt, skip, ignored, i, like, code; bm25 rerank score=34.858; matched issue terms: fmt, skip, ignored, i, like, code; bm25 rerank score=34.858; matched issue terms: fmt, skip, ignored, i, like, code
- src/black/comments.py: path components match issue terms, source file; bm25 rerank score=17.836; matched issue terms: fmt, skip, ignored, i, like, format; bm25 rerank score=22.440; matched issue terms: fmt, skip, ignored, i, like, format; bm25 rerank score=31.468; matched issue terms: fmt, skip, ignored, i, like, format; bm25 rerank score=31.468; matched issue terms: fmt, skip, ignored, i, like, format

Attempts:
Attempt 1: success=False
File: src/black/linegen.py
Result: {"command": "/tmp/repopilot-psf-black-9o0kobgg-venv/bin/python -m pytest tests/", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/repopilot-psf-black-9o0kobgg-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/tmp/repopilot-psf-black-9o0kobgg-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repopilot-psf-black-9o0kobgg-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repopilot-psf-black-9o0kobgg-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repopilot-psf-black-9o0kobgg-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/repopilot-psf-black-9o0kobgg-venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name

Attempt 2: success=False
File: src/black/linegen.py
Result: patch_apply_failed
Error:
Search/replace edit failed: edit 1 search block was not found in src/black/linegen.py.

Attempt 3: success=False
File: src/black/comments.py
Result: patch_apply_failed
Error:
Search/replace edit failed: edit 1 search block was not found in src/black/comments.py.

Attempt 4: success=False
File: src/black/linegen.py
Result: patch_apply_failed
Error:
Search/replace edit failed: edit 1 search block was not found in src/black/linegen.py.

Token usage: 80749/100000
