### ISSUE TITLE
Failed to build mypyc enabled wheel on armv7 (32bit) machine

### ISSUE THREAD

**Issue by isac322** [psf/black#3376]
**Describe the bug**

Failed to build wheel using mypyc on armv7 machine.

**To Reproduce**

Build [Dockerfile](https://github.com/isac322/docker_image_blackd/blob/c5d0e377bbd77dcb01a4a25f1cc02d4180106216/Dockerfile) with build-arg `VERSION=22.10.0` on armv7 machine.

The resulting error is:

```
2022-11-06T05:46:57.1207824Z #49 [linux/arm/v7 builder 10/13] RUN env       MAKEFLAGS="-j$(nproc)"       HATCH_BUILD_HOOKS_ENABLE=1 HATCH_BUILD_CLEAN_HOOKS_AFTER=1       MYPYC_OPT_LEVEL=3 MYPYC_DEBUG_LEVEL=0 AIOHTTP_NO_EXTENSIONS=1 CC=clang       python -m build --wheel
2022-11-06T05:46:58.7282203Z #49 1.738 * Creating venv isolated environment...
2022-11-06T05:47:35.6721922Z #49 38.68 * Installing packages in isolated environment... (hatch-fancy-pypi-readme, hatch-vcs, hatchling>=1.8.0)
2022-11-06T05:47:55.5159109Z #49 58.47 * Getting build dependencies for wheel...
2022-11-06T05:47:57.0194635Z #49 59.97 /tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/setuptools_scm/git.py:135: UserWarning: "/black" is shallow and may cause errors
2022-11-06T05:47:57.0195349Z #49 59.97   warnings.warn(f'"{wd.path}" is shallow and may cause errors')
2022-11-06T05:47:58.0719397Z #49 60.94 * Installing packages in isolated environment... (click>=8.0.0, hatch-mypyc>=0.13.0, mypy-extensions>=0.4.3, mypy==0.971, pathspec>=0.9.0, platformdirs>=2, tomli>=1.1.0; python_full_version < '3.11.0a7', typed-ast>=1.4.2; python_version < '3.8' and implementation_name == 'cpython', types-typed-ast>=1.4.2, typing-extensions>=3.10.0.0; python_version < '3.10')
2022-11-06T05:48:17.4417729Z #49 80.45 * Building wheel...
2022-11-06T05:48:18.9285906Z #49 81.94 /tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/setuptools_scm/git.py:135: UserWarning: "/black" is shallow and may cause errors
2022-11-06T05:48:18.9286597Z #49 81.94   warnings.warn(f'"{wd.path}" is shallow and may cause errors')
2022-11-06T05:52:11.5630204Z #49 314.6 Traceback (most recent call last):
2022-11-06T05:52:11.7139700Z #49 314.6   File "/usr/local/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
2022-11-06T05:52:11.7140123Z #49 314.6     main()
2022-11-06T05:52:11.7140646Z #49 314.6   File "/usr/local/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 333, in main
2022-11-06T05:52:11.7141199Z #49 314.6     json_out['return_val'] = hook(**hook_input['kwargs'])
2022-11-06T05:52:11.7141534Z #49 314.6                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-11-06T05:52:11.7142086Z #49 314.6   File "/usr/local/lib/python3.11/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
2022-11-06T05:52:11.7142569Z #49 314.6     return _build_backend().build_wheel(wheel_directory, config_settings,
2022-11-06T05:52:11.7142941Z #49 314.6            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-11-06T05:52:11.7143531Z #49 314.6   File "/tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/hatchling/build.py", line 41, in build_wheel
2022-11-06T05:52:11.7144156Z #49 314.6     return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
2022-11-06T05:52:11.7144545Z #49 314.6                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-11-06T05:52:11.7145173Z #49 314.6   File "/tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 136, in build
2022-11-06T05:52:11.7145631Z #49 314.6     build_hook.initialize(version, build_data)
2022-11-06T05:52:11.7146242Z #49 314.6   File "/tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/hatch_mypyc/plugin.py", line 338, in initialize
2022-11-06T05:52:11.7146896Z #49 314.6     raise Exception(f'Error while invoking Mypyc:\n{process.stdout.decode("utf-8")}')
2022-11-06T05:52:11.7147309Z #49 314.6 Exception: Error while invoking Mypyc:
2022-11-06T05:52:11.7147585Z #49 314.6 running build_ext
2022-11-06T05:52:11.7148012Z #49 314.6 building '6b397dd64e00b5aff23d__mypyc' extension
2022-11-06T05:52:11.7148674Z #49 314.6 creating /tmp/tmps2ggz8u6/tmp/tmp
2022-11-06T05:52:11.7149005Z #49 314.6 creating /tmp/tmps2ggz8u6/tmp/tmp/tmps2ggz8u6
2022-11-06T05:52:11.7149370Z #49 314.6 creating /tmp/tmps2ggz8u6/tmp/tmp/tmps2ggz8u6/build
2022-11-06T05:52:11.7151137Z #49 314.6 clang -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/mypyc/lib-rt -I/tmp/tmps2ggz8u6/build -I/tmp/build-env-wxt3bwpz/include -I/usr/local/include/python3.11 -c /tmp/tmps2ggz8u6/build/__native_6b397dd64e00b5aff23d.c -o /tmp/tmps2ggz8u6/tmp/tmp/tmps2ggz8u6/build/__native_6b397dd64e00b5aff23d.o -O3 -g0 -Werror -Wno-unused-function -Wno-unused-label -Wno-unreachable-code -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-warning-option
2022-11-06T05:52:11.7152304Z #49 314.6 In file included from /tmp/tmps2ggz8u6/build/__native_6b397dd64e00b5aff23d.c:4:
2022-11-06T05:52:11.7153236Z #49 314.6 /tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/mypyc/lib-rt/int_ops.c:349:17: error: comparison of integers of different signs: 'Py_ssize_t' (aka 'int') and 'digit' (aka 'unsigned int') [-Werror,-Wsign-compare]
2022-11-06T05:52:11.7153801Z #49 314.6         if (val > PyLong_MASK) {
2022-11-06T05:52:11.7154060Z #49 314.6             ~~~ ^ ~~~~~~~~~~~
2022-11-06T05:52:11.7154883Z #49 314.6 /tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/mypyc/lib-rt/int_ops.c:352:21: error: comparison of integers of different signs: 'Py_ssize_t' (aka 'int') and 'digit' (aka 'unsigned int') [-Werror,-Wsign-compare]
2022-11-06T05:52:11.7155444Z #49 314.6             if (val > PyLong_MASK) {
2022-11-06T05:52:11.7155723Z #49 314.6                 ~~~ ^ ~~~~~~~~~~~
2022-11-06T05:52:11.7155968Z #49 314.6 2 errors generated.
2022-11-06T05:52:11.7156394Z #49 314.6 error: command '/usr/bin/clang' failed with exit code 1
2022-11-06T05:52:11.7156687Z #49 314.6 
2022-11-06T05:52:11.9859480Z #49 315.0 
2022-11-06T05:52:12.1292221Z #49 315.0 ERROR Backend subprocess exited when trying to invoke build_wheel
2022-11-06T05:52:12.1294026Z #49 ERROR: process "/bin/sh -c env       MAKEFLAGS=\"-j$(nproc)\"       HATCH_BUILD_HOOKS_ENABLE=1 HATCH_BUILD_CLEAN_HOOKS_AFTER=1       MYPYC_OPT_LEVEL=3 MYPYC_DEBUG_LEVEL=0 AIOHTTP_NO_EXTENSIONS=1 CC=clang       python -m build --wheel" did not complete successfully: exit code: 1
2022-11-06T05:52:12.1294560Z 
2022-11-06T05:52:12.1295253Z #46 [linux/arm64 builder 10/13] RUN env       MAKEFLAGS="-j$(nproc)"       HATCH_BUILD_HOOKS_ENABLE=1 HATCH_BUILD_CLEAN_HOOKS_AFTER=1       MYPYC_OPT_LEVEL=3 MYPYC_DEBUG_LEVEL=0 AIOHTTP_NO_EXTENSIONS=1 CC=clang       python -m build --wheel
2022-11-06T05:52:12.2193471Z #46 CANCELED
2022-11-06T05:52:12.2204556Z ------
2022-11-06T05:52:12.2242509Z  > [linux/arm/v7 builder 10/13] RUN env       MAKEFLAGS="-j$(nproc)"       HATCH_BUILD_HOOKS_ENABLE=1 HATCH_BUILD_CLEAN_HOOKS_AFTER=1       MYPYC_OPT_LEVEL=3 MYPYC_DEBUG_LEVEL=0 AIOHTTP_NO_EXTENSIONS=1 CC=clang       python -m build --wheel:
2022-11-06T05:52:12.2243446Z #49 314.6         if (val > PyLong_MASK) {
2022-11-06T05:52:12.2245402Z #49 314.6             ~~~ ^ ~~~~~~~~~~~
2022-11-06T05:52:12.2247016Z #49 314.6 /tmp/build-env-wxt3bwpz/lib/python3.11/site-packages/mypyc/lib-rt/int_ops.c:352:21: error: comparison of integers of different signs: 'Py_ssize_t' (aka 'int') and 'digit' (aka 'unsigned int') [-Werror,-Wsign-compare]
2022-11-06T05:52:12.2247701Z #49 314.6             if (val > PyLong_MASK) {
2022-11-06T05:52:12.2248369Z #49 314.6                 ~~~ ^ ~~~~~~~~~~~
2022-11-06T05:52:12.2249613Z #49 314.6 2 errors generated.
2022-11-06T05:52:12.2250158Z #49 314.6 error: command '/usr/bin/clang' failed with exit code 1
2022-11-06T05:52:12.2251695Z #49 314.6 
2022-11-06T05:52:12.2252358Z #49 315.0 
2022-11-06T05:52:12.2252777Z #49 315.0 ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Environment**

- Black's version: 22.10.0
- OS and Python version: Linux/Python 3.11

**Additional context**

mypyc fixed this issue on https://github.com/python/mypy/pull/13239 and released it to 0.981 but hatch-mypyc and black pin mypy version to 0.971.
<strike>To fix this, hatch-mypyc should bump up mypy first (https://github.com/ofek/hatch-mypyc/issues/23).</strike> Turns out hatch-mypyc already support 0.981.

**Comment by ichard26** [comment]
Hey, I manage our mypyc deployment. I didn't know mypyc supported armv7! I'll look into upgrading the toolchain soon -- thanks for the heads up!
