### ISSUE TITLE
Segmentation fault when trying to run `black`

### ISSUE THREAD

**Issue by ZeroIntensity** [psf/black#3482]
*not using the issue report format since it doesnt really fit here*

originally, i was having an issue that looked like this:
```
> black
Traceback (most recent call last):
  File "/home/zero/.local/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1481, in patched_main
KeyError: 'maybe_install_uvloop
```
 i then updated through `python3 -m pip install -U black`. 
now, instead when i run black (both through `black` and `python3 -m black`), i get a segfault.

heres what it looks like when i run it through valgrind:

```
==6446== Invalid read of size 8
==6446==    at 0x62BE30A: CPyDef_black___patch_click (in /home/zero/.local/lib/python3.10/site-packages/6b397dd64e00b5aff23d__mypyc.cpython-310-x86_64-linux-gnu.so)
==6446==    by 0x62BEE46: CPyDef_black___patched_main (in /home/zero/.local/lib/python3.10/site-packages/6b397dd64e00b5aff23d__mypyc.cpython-310-x86_64-linux-gnu.so)
==6446==    by 0x62BF015: CPyPy_black___patched_main (in /home/zero/.local/lib/python3.10/site-packages/6b397dd64e00b5aff23d__mypyc.cpython-310-x86_64-linux-gnu.so)
==6446==    by 0x49BC73E: ??? (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x49B4B15: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x49B375F: ??? (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x4A60E03: PyEval_EvalCode (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x4A715B2: ??? (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x4A6CD09: ??? (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x49111CC: ??? (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x4910E7D: _PyRun_SimpleFileObject (in /usr/lib/libpython3.10.so.1.0)
==6446==    by 0x4911830: _PyRun_AnyFileObject (in /usr/lib/libpython3.10.so.1.0)
==6446==  Address 0x130 is not stack'd, malloc'd or (recently) free'd
```

however, i can still import black and use it from there, as shown:

```
> python3 -c "import black; print(black.__file__)"
/home/zero/.local/lib/python3.10/site-packages/black/__init__.cpython-310-x86_64-linux-gnu.so
> python3 -c "import black; print(black.__version__)"
22.12.0
```

i am running python 3.10 with arch linux.

**Comment by ZeroIntensity** [comment]
weird, installing via `pipx` seemed to fix it. will leave this open in case it appears again in the future.

**Comment by JelleZijlstra** [comment]
Closing as we haven't had other reports.

**Comment by ZeroIntensity** [comment]
Likely was an issue with mypyc (or whatever you guys use for compiling) and not black.

**Comment by JelleZijlstra** [comment]
Yes, or with CPython even, or with something weird on your system. If mypyc causes Black to break, we generally do want to know about it, so we can work around it or contribute an upstream fix. In this case there is nothing reproducible to fix though.
