### ISSUE TITLE
Preview crashes on await (yield)

### ISSUE THREAD

**Issue by jakkdl** [psf/black#3532]
**Describe the bug**
`black --preview` crashes on seeing `await (yield)`
This is certainly not good code or anything, but is code we have [in one of our test files](https://github.com/Zac-HD/flake8-trio/blob/ec04f75f6c58515f58316870272fab315b828a35/tests/eval_files/trio108.py#L31-L34) in flake8-trio. Non-preview black has no issues with it.

**To Reproduce**

For example, take this code:

```python
async def foo():
    await (yield)
```

And run it with these arguments:

```sh
$ black --preview myfile.py 
```

The resulting error is:

```
error: cannot format myfile.py: blib2to3.pytree.Node object expected; got blib2to3.pytree.Leaf

Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior**

Not crashing

**Environment**

```sh
$ black --version
black, 22.12.0 (compiled: yes)
Python (CPython) 3.11.0
$ python --version
Python 3.11.0
$ uname -sro
Linux 6.1.1-arch1-1 GNU/Linux
```

**Comment by JelleZijlstra** [comment]
Thanks! We'll fix this before the stable release.

**Comment by JelleZijlstra** [comment]
Note this only repros with mypyc enabled. This is the stack trace (from `black -v`):

```
Traceback (most recent call last):
  File "src/black/__init__.py", line 770, in reformat_one
  File "src/black/__init__.py", line 810, in format_file_in_place
  File "src/black/__init__.py", line 926, in format_file_contents
  File "src/black/__init__.py", line 1073, in format_str
  File "src/black/__init__.py", line 1100, in _format_str_once
  File "src/black/nodes.py", line 169, in visit
  File "src/black/linegen.py", line 139, in visit_default
  File "src/black/nodes.py", line 175, in visit_default
  File "src/black/nodes.py", line 167, in visit
  File "src/black/linegen.py", line 265, in visit_async_stmt
  File "src/black/nodes.py", line 167, in visit
  File "src/black/linegen.py", line 222, in visit_suite
  File "src/black/linegen.py", line 139, in visit_default
  File "src/black/nodes.py", line 175, in visit_default
  File "src/black/nodes.py", line 167, in visit
  File "src/black/linegen.py", line 248, in visit_simple_stmt
  File "src/black/linegen.py", line 139, in visit_default
  File "src/black/nodes.py", line 175, in visit_default
  File "src/black/nodes.py", line 167, in visit
  File "src/black/linegen.py", line 294, in visit_power
  File "src/black/linegen.py", line 1075, in remove_await_parens
TypeError: blib2to3.pytree.Node object expected; got blib2to3.pytree.Leaf
```

I think I found the cause; it's a bad `cast`. I'll propose a fix.

**Comment by jakkdl** [comment]
Nice and quick, thanks!
