### ISSUE TITLE
AttributeError in format_file_contents

### ISSUE THREAD

**Issue by DavidKorczynski** [psf/black#3605]
**Describe the bug**
An uncaught exception is raised in `format_file_contents`.

```python
import sys
import atheris
import black


def TestOneInput(data):
  fdp = atheris.FuzzedDataProvider(data)
  try:
    black.format_file_contents(fdp.ConsumeUnicodeNoSurrogates(fdp.ConsumeIntInRange(0, 2048)),
                               mode=black.Mode(),
                               fast=fdp.ConsumeBool())
  except black.InvalidInput:
    pass
  except black.NothingChanged:
    pass


data = (b"\x41\x28\x65\x43\x8f\x28\x65\x2c\x29\x66\x6f\x72\x0a\x23\x0a\x0a\x0a\xb8\x32\x2a\x2a\x36\x28\x69\x29\x69\x6e\x28\x29\x29\x2c\x68\x30\x69")
TestOneInput(data)
```

The stacktrace produced:
```
	 === Uncaught Python exception: ===
AttributeError: 'Leaf' object has no attribute 'bracket_depth'
Traceback (most recent call last):
  File "fuzz_format_filecontents.py", line 25, in TestOneInput
  File "black/__init__.py", line 932, in format_file_contents
  File "black/__init__.py", line 1079, in format_str
  File "black/__init__.py", line 1114, in _format_str_once
  File "black/linegen.py", line 587, in transform_line
  File "black/linegen.py", line 1504, in run_transformer
  File "black/linegen.py", line 587, in transform_line
  File "black/linegen.py", line 1504, in run_transformer
  File "black/linegen.py", line 587, in transform_line
  File "black/linegen.py", line 1504, in run_transformer
  File "black/linegen.py", line 587, in transform_line
  File "black/linegen.py", line 1504, in run_transformer
  File "black/linegen.py", line 509, in transform_line
  File "black/lines.py", line 739, in is_line_short_enough
  File "black/lines.py", line 201, in contains_standalone_comments
AttributeError: 'Leaf' object has no attribute 'bracket_depth'
```

**To Reproduce**
Run the program above against latest black (from source). The `atheris` module used is https://pypi.org/project/atheris/

**Environment**

Ubuntu 20.04, compiled with latest code from Github.

**Additional context**

This was found by way of OSS-Fuzz and the set up here: https://github.com/google/oss-fuzz/tree/master/projects/black If you find this issue helpful then it would be great to have maintainer emails in the `project.yaml` to receive notifications of bug reports, which contain all of the details similar to what I posted above.

**Comment by ichard26** [comment]
Thanks for the bug report! This is quite low priority given that's some esoteric "code" haha :)

**Comment by MeGaGiGaGon** [comment]
The referenced code was 
```py
    def contains_standalone_comments(self, depth_limit: int = sys.maxsize) -> bool:
        """If so, needs to be split before emitting."""
        for leaf in self.leaves:
            if leaf.type == STANDALONE_COMMENT and leaf.bracket_depth <= depth_limit:
                return True

        return False
```
but the usage of `leaf.bracket_depth` has since been removed by #4016, so this crash is no longer possible. I may be missing it, but I don't see the input that lead to the crash, so I don't think any tests could be made for it. If that's the case, this should be good to close.

**Comment by hauntsaninja** [comment]
Thanks for fuzzing Black! Do let us know if you find other interesting things, feel free to put hauntsaninja+black at gmail dot com in your point of contact

Agree with MeGaGiGaGon that this should no longer be possible
