### ISSUE TITLE
Black fails to determine version if a file named 'secrets.py' is present in the repository

### ISSUE THREAD

**Issue by samskiter** [psf/black#3906]
**Describe the bug**

As per this stackoverflow: https://stackoverflow.com/questions/70961301/black-not-formatting-python-code-from-vscode
And this one: https://stackoverflow.com/questions/66846608/attributeerror-module-secrets-has-no-attribute-token-bytes

Having a 'secrets.py' present in the repository causes black to fail on startup within VSCode

**To Reproduce**

1. Setup black to run in VSCode (use the black formatter extension)
2. Add a file names 'secrets.py' to the project
3. Restart VSCode

The resulting error is:

```
Error while detecting black version:
Traceback (most recent call last):
  File "/Users/samduke/.vscode/extensions/ms-python.black-formatter-2023.4.1/bundled/tool/lsp_server.py", line 224, in _log_version_info
    result = _run_tool(["--version"], settings)
  File "/Users/samduke/.vscode/extensions/ms-python.black-formatter-2023.4.1/bundled/tool/lsp_server.py", line 505, in _run_tool
    result = utils.run_module(
  File "/Users/samduke/.vscode/extensions/ms-python.black-formatter-2023.4.1/bundled/tool/lsp_utils.py", line 147, in run_module
    return _run_module(module, argv, use_stdin, source)
  File "/Users/samduke/.vscode/extensions/ms-python.black-formatter-2023.4.1/bundled/tool/lsp_utils.py", line 134, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 220, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "src/black/__init__.py", line 45, in <module>
  File "[...]/lib/python3.10/site-packages/black/files.py", line 36, in <module>
    from black.handle_ipynb_magics import jupyter_dependencies_are_installed
  File "src/black/handle_ipynb_magics.py", line 50, in <module>
AttributeError: module 'secrets' has no attribute 'token_hex'```

**Expected behavior**

Be able to add and use a file named secrets.py 

**Environment**

- Black's version: 23.9.1
- OS and Python version: macOS 13.5.1 (22G90)
- VSCode: 1.82.1 (Universal)
- Black formatter extension: v2023.4.1
- Python Extension: v2023.16.0
- Pylance extension: v2023.16.0

**Comment by hauntsaninja** [comment]
This isn't a bug in black. In general, Python will put the current directory on sys.path. If you have a module that shadows a standard library module, it will cause problems. See e.g. https://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap
