### ISSUE TITLE
AttributeError: 'split_wrapper_dont_increase_indentation_obj' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by wimglenn** [psf/black#3980]
Trying to get a compiled black on 3.12 (the wheel on PyPI is not)

I'm building from tag 23.10.1 on Python 3.12.0 with the following:

```
HATCH_BUILD_HOOKS_ENABLE=1 MYPYC_OPT_LEVEL=3 MYPYC_DEBUG_LEVEL=0 CC=clang AIOHTTP_NO_EXTENSIONS=1 pip install -vv .
```

The build succeeds but the app crashes

```
$ .venv/bin/black
Traceback (most recent call last):
  File ".../.venv/bin/black", line 5, in <module>
    from black import patched_main
  File "src/black/__init__.py", line 64, in <module>
    from black.linegen import LN, LineGenerator, transform_line
  File "src/black/linegen.py", line 1080, in <module>
    @dont_increase_indentation
  File "src/black/linegen.py", line 1051, in dont_increase_indentation
    def split_wrapper(
  File ".../lib/python3.12/functools.py", line 58, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'split_wrapper_dont_increase_indentation_obj' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

**Comment by JelleZijlstra** [comment]
That's why we don't distribute 3.12 wheels. This was reported in python/mypy#16077 and the fix should be in the next mypy release.
