### ISSUE TITLE
FIPS compliance for --diff 

### ISSUE THREAD

**Issue by acestronautical** [psf/black#4059]
When running:
```
black -l 80 --check --diff .
```
On a system configured for FIPS, the command fails with:
```
Traceback (most recent call last):
  File "/usr/local/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1504, in patched_main
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "src/black/__init__.py", line 638, in main
  File "/usr/local/lib/python3.10/dist-packages/black/concurrency.py", line 101, in reformat_many
    loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/black/concurrency.py", line 152, in schedule_formatting
    lock = manager.Lock()
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 723, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 606, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 755, in answer_challenge
    digest = hmac.new(authkey, message, 'md5').digest()
  File "/usr/lib/python3.10/hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.10/hmac.py", line 60, in __init__
    self._init_hmac(key, msg, digestmod)
  File "/usr/lib/python3.10/hmac.py", line 67, in _init_hmac
    self._hmac = _hashopenssl.hmac_new(key, msg, digestmod=digestmod)
ValueError: [digital envelope routines] unsupported
```

The root cause seems to be upstream at https://github.com/python/cpython/issues/61460

**Comment by hauntsaninja** [comment]
Yeah, I think you'll need to use 3.12 that has the upstream fix. FIPS support isn't enough of a priority for black that we would hack or fork multiprocessing to make things work on older Python

**Comment by acestronautical** [comment]
Thanks for responding. It makes sense not to fix this in Black. Hopefully this closed issue serves as documentation for somebody.
