### ISSUE TITLE
blackd: Invalid method encountered

### ISSUE THREAD

**Issue by albertz** [psf/black#4207]
**Describe the bug**

I want to use blackd together with PyCharm (standalone or via Gateway). This has worked fine all the time, for a long time, many different versions, many different environments. Now suddenly, I get a strange error in PyCharm:

With PyCharm (via Gateway), when I try to check the connection, I get:
```
Cannot connect to blackd:  Unsupported or unrecognized SSL message
```

When I run blackd directly in the shell, I see this error `Invalid method encountered` once I try to check the connection:

```
$ blackd --bind-port 45485
blackd version 22.3.0 listening on localhost port 45485
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/u/zeyer/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x03\x01\xcb\x01'
      ^
INFO:aiohttp.access:127.0.0.1 [03/Feb/2024:21:25:06 +0000] "UNKNOWN / HTTP/1.0" 400 225 "-" "-"
```
Or with newer black:
```
blackd version 24.1.1 listening on localhost port 45485
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/u/zeyer/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x03\x01\xcb\x01'
      ^
INFO:aiohttp.access:127.0.0.1 [03/Feb/2024:21:30:19 +0000] "UNKNOWN / HTTP/1.0" 400 225 "-" "-"
```
I also updated aiohttp to 3.9.3.

I currently have no idea where this problem can come from... Also, a Google search revealed no single such error on the Internet.

(Not sure if this is an issue of blackd, of PyCharm, or of some other component. I just wanted to report it somewhere.)

**Environment**

- Black's version: 24.1.1
- OS and Python version: Ubuntu 22.04 Linux, Python 3.10

**Comment by albertz** [comment]
Ok, I found the issue: In PyCharm, for some reason, the "Use SSL" checkbox was enabled. I don't think I changed this, but maybe I misclicked it... It should be disabled. Now it works again.
