### ISSUE TITLE
Running black in module mode conflicts with certain package names

### ISSUE THREAD

**Issue by toriningen** [psf/black#4250]
**Describe the bug**

When Black is applied to a folder that has a package or module named "token", it will fail:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "src\black\__init__.py", line 6, in <module>
    <part of code being formatted from __init__.py of current directory, for some strange reason>
  File "C:\Program Files\Python312\Lib\tokenize.py", line 36, in <module>
    from token import EXACT_TOKEN_TYPES
ImportError: cannot import name 'EXACT_TOKEN_TYPES' from 'token' (<path to current directory>\token\__init__.py)```

**To Reproduce**

Create a new folder:
```sh
$ mkdir foo
```

Put a file named "token.py" there:
```sh
$ touch foo/token.py
```

Run Black from that new folder:
```sh
$ cd test
$ python -m black
```

It crashes with:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "src\black\__init__.py", line 6, in <module>
  File "C:\Program Files\Python312\Lib\tokenize.py", line 36, in <module>
    from token import EXACT_TOKEN_TYPES
ImportError: cannot import name 'EXACT_TOKEN_TYPES' from 'token' (D:\test-black-bug\foo\token.py)
```

**Expected behavior**

Black shouldn't be affected by module names in the projects it formats.

**Environment**

- Black's version: 24.2.0 (compiled: yes)
- OS and Python version: Windows 11 23H2 (22631.3155), Python 3.12.2

**Additional context**

When being ran as a script, it works.

**Comment by hauntsaninja** [comment]
This is just how Python imports work. `token` is a standard library module. If you're using Python 3.11 or newer you can set `PYTHONSAFEPATH` or pass `-P` to `python` to change Python's cwd import behaviour
