### ISSUE TITLE
AttributeError: module 'black' has no attribute 'Mode'. Did you mean: 'mode'?

### ISSUE THREAD

**Issue by devxpy** [psf/black#4274]
My CI keeps failing because I have used the black formatter in my code to [render code snippets on the frontend](http://gooey.ai/copilot/api). Its hard to reproduce, and only happens intermittently when I run a lot of tests. Is there perhaps a better way to use black?

**To Reproduce**

For example, take this code:

```python
import black

py_code = black.format_str(py_code, mode=black.Mode())
```

And run it with these arguments:

```sh
$ pytest -n 2
```

The resulting error is:

```
Step #2: pytest_1    | ______________________ test_all_slugs [/art-qr-code/api] _______________________
Step #2: pytest_1    | [gw0] linux -- Python 3.10.12 /root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/bin/python
Step #2: pytest_1    | Traceback (most recent call last):
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/pytest_subtests.py", line 202, in test
Step #2: pytest_1    |     yield
Step #2: pytest_1    |   File "/app/conftest.py", line 73, in runner
Step #2: pytest_1    |     return fn(*args, **kwargs)
Step #2: pytest_1    |   File "/app/tests/test_public_endpoints.py", line 65, in _test_post_path
Step #2: pytest_1    |     r = client.post(url, json={}, allow_redirects=True)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
Step #2: pytest_1    |     return self.request("POST", url, data=data, json=json, **kwargs)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/testclient.py", line 473, in request
Step #2: pytest_1    |     return super().request(
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
Step #2: pytest_1    |     resp = self.send(prep, **send_kwargs)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 725, in send
Step #2: pytest_1    |     history = [resp for resp in gen]
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 725, in <listcomp>
Step #2: pytest_1    |     history = [resp for resp in gen]
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
Step #2: pytest_1    |     resp = self.send(
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
Step #2: pytest_1    |     r = adapter.send(request, **kwargs)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/testclient.py", line 267, in send
Step #2: pytest_1    |     raise exc
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/testclient.py", line 264, in send
Step #2: pytest_1    |     portal.call(self.app, scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/anyio/from_thread.py", line 277, in call
Step #2: pytest_1    |     return cast(T_Retval, self.start_task_soon(func, *args).result())
Step #2: pytest_1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
Step #2: pytest_1    |     return self.__get_result()
Step #2: pytest_1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
Step #2: pytest_1    |     raise self._exception
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/anyio/from_thread.py", line 217, in _call_func
Step #2: pytest_1    |     retval = await retval
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
Step #2: pytest_1    |     await super().__call__(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
Step #2: pytest_1    |     await self.middleware_stack(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
Step #2: pytest_1    |     raise exc
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
Step #2: pytest_1    |     await self.app(scope, receive, _send)
Step #2: pytest_1    |   File "/app/server.py", line 78, in middleware
Step #2: pytest_1    |     await app(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 86, in __call__
Step #2: pytest_1    |     await self.app(scope, receive, send_wrapper)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/authentication.py", line 48, in __call__
Step #2: pytest_1    |     await self.app(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
Step #2: pytest_1    |     await self.app(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
Step #2: pytest_1    |     raise exc
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
Step #2: pytest_1    |     await self.app(scope, receive, sender)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Step #2: pytest_1    |     raise e
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Step #2: pytest_1    |     await self.app(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
Step #2: pytest_1    |     await route.handle(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
Step #2: pytest_1    |     await self.app(scope, receive, send)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
Step #2: pytest_1    |     response = await func(request)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
Step #2: pytest_1    |     raw_response = await run_endpoint_function(
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
Step #2: pytest_1    |     return await run_in_threadpool(dependant.call, **values)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
Step #2: pytest_1    |     return await anyio.to_thread.run_sync(func, *args)
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
Step #2: pytest_1    |     return await get_asynclib().run_sync_in_worker_thread(
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
Step #2: pytest_1    |     return await future
Step #2: pytest_1    |   File "/root/.cache/pypoetry/virtualenvs/ddgai-9TtSrW0h-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
Step #2: pytest_1    |     result = context.run(func, *args)
Step #2: pytest_1    |   File "/app/routers/root.py", line 374, in st_page
Step #2: pytest_1    |     ret = st.runner(
Step #2: pytest_1    |   File "/app/gooey_ui/state.py", line 130, in runner
Step #2: pytest_1    |     fn()
Step #2: pytest_1    |   File "/app/routers/root.py", line 375, in <lambda>
Step #2: pytest_1    |     lambda: page_wrapper(request, page.render),
Step #2: pytest_1    |   File "/app/routers/root.py", line 428, in page_wrapper
Step #2: pytest_1    |     render_fn(**kwargs)
Step #2: pytest_1    |   File "/app/daras_ai_v2/base.py", line 241, in render
Step #2: pytest_1    |     self.render_selected_tab(self.tab)
Step #2: pytest_1    |   File "/app/daras_ai_v2/base.py", line 748, in render_selected_tab
Step #2: pytest_1    |     self.run_as_api_tab()
Step #2: pytest_1    |   File "/app/daras_ai_v2/base.py", line 1826, in run_as_api_tab
Step #2: pytest_1    |     api_example_generator(
Step #2: pytest_1    |   File "/app/daras_ai_v2/api_examples_widget.py", line 187, in api_example_generator
Step #2: pytest_1    |     py_code = black.format_str(py_code, mode=black.Mode())
Step #2: pytest_1    | AttributeError: module 'black' has no attribute 'Mode'. Did you mean: 'mode'?
```

**Environment**

- Black's version: `24.2.0`
- OS and Python version: `library/python:3.10.12-slim-bookworm`

**Comment by JelleZijlstra** [comment]
> Is there perhaps a better way to use black?

Yes, you can invoke the `black` command-line tool. That is currently the only supported way to use Black.

However, `black.Mode` should exist; it's always exported: https://github.com/psf/black/blob/1abcffc81816257985678f08c61584ed4287f22a/src/black/__init__.py#L70. If you are not seeing it, there's probably something wrong in your environment.
