### ISSUE TITLE
Black failed to reformat

### ISSUE THREAD

**Issue by mcnuggetsx20** [psf/black#4407]
I cannot use black to reformat my file. Here is the output of ```black --versbose test.py```
```Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/black/__init__.py", line 902, in reformat_one
    if changed is not Changed.CACHED and format_file_in_place(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/black/__init__.py", line 944, in format_file_in_place
    dst_contents = format_file_contents(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/black/__init__.py", line 1070, in format_file_contents
    dst_contents = format_str(src_contents, mode=mode, lines=lines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/black/__init__.py", line 1225, in format_str
    dst_contents = _format_str_once(src_contents, mode=mode, lines=lines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/black/__init__.py", line 1239, in _format_str_once
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/black/parsing.py", line 90, in lib2to3_parse
    raise exc from None
black.parsing.InvalidInput: Cannot parse: 3:0: pass
error: cannot format test.py: Cannot parse: 3:0: pass

Oh no! 💥 💔 💥
1 file failed to reformat.
```

I'm also attaching the content of test.py
```py
a = 5
if a == 5:
pass
```

System: Arch Linux 6.9.10-arch1-1
Installed black with pacman (python-black)

**Comment by hauntsaninja** [comment]
The input needs to be valid Python syntax, yours is missing indentation.
